import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ArtButton, ArtInput, ArtLabel, TextValueAccessor } from '@aranghat/base-angular';

@Component({
  selector: 'sample-input-form',
  // TextValueAccessor bridges art-input to ngModel / reactive forms (generated by the Angular output target)
  imports: [FormsModule, ArtButton, ArtInput, ArtLabel, TextValueAccessor],
  template: `
    <form (submit)="onSubmit($event)">
      <art-label for="username">Username</art-label>
      <art-input id="username" name="username" placeholder="shadcn" required [minlength]="2" [(ngModel)]="username"></art-input>
      <art-button type="submit">Submit</art-button>
      <art-button type="reset" variant="ghost" (click)="username = ''">Reset</art-button>
    </form>
  `,
})
export class InputForm {
  username = '';
  onSubmit(e: Event) {
    e.preventDefault();
    console.log('submitted', Object.fromEntries(new FormData(e.target as HTMLFormElement)), this.username);
  }
}
