import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ArtButton, ArtLabel } from '@aranghat/base-angular';
import { ArtDatePicker, SelectValueAccessor } from '@aranghat/components-angular';

@Component({
  selector: 'sample-date-picker-form',
  // SelectValueAccessor bridges art-date-picker to ngModel / reactive forms (generated by the Angular output target)
  imports: [FormsModule, ArtButton, ArtLabel, ArtDatePicker, SelectValueAccessor],
  template: `
    <form (submit)="onSubmit($event)">
      <art-label for="dob">Date of birth</art-label>
      <art-date-picker id="dob" name="dob" caption-layout="dropdown" min="1900-01-01" max="2026-12-31" required [(ngModel)]="dob"></art-date-picker>
      <art-button type="submit">Submit</art-button>
    </form>
  `,
})
export class DatePickerForm {
  dob = '';
  onSubmit(e: Event) {
    e.preventDefault();
    console.log('submitted', Object.fromEntries(new FormData(e.target as HTMLFormElement)), this.dob);
  }
}
