#!/usr/bin/env node
/**
 * Usage: artui-wrapper-entries <framework: react|vue|angular|core> <tier>
 *
 * Reads packages/<tier>/dist/docs.json and generates:
 *   react/vue : src/index.ts + src/<name>.ts  → `export { ArtButton as Button } ...`
 *   angular   : src/public-api.ts             → re-exports proxies (selector stays art-*)
 *   core      : nothing generated; only exports updated (`@aranghat/base/button`)
 * and rewrites the package's `exports` map so every component has a subpath.
 * Idempotent; CI fails if it produces a diff.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, resolve } from 'node:path';

const [framework, tier] = process.argv.slice(2);
if (!framework || !tier) { console.error('usage: artui-wrapper-entries <react|vue|angular|core> <tier>'); process.exit(2); }

const repo = resolve(import.meta.dirname, '../..');
const docs = JSON.parse(readFileSync(join(repo, 'packages', tier, 'dist', 'docs.json'), 'utf8'));
const tags = docs.components.map((c) => c.tag).sort();
const pascal = (tag) => tag.split('-').map((p) => p[0].toUpperCase() + p.slice(1)).join('');
const unprefixed = (tag) => pascal(tag.replace(/^art-/, ''));
const slug = (tag) => tag.replace(/^art-/, '');

const pkgDir = framework === 'core' ? join(repo, 'packages', tier) : join(repo, 'packages', framework, tier);
const pkgPath = join(pkgDir, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const exportsMap = { '.': pkg.exports?.['.'] };

if (framework === 'react' || framework === 'vue') {
  const srcDir = join(pkgDir, 'src');
  mkdirSync(srcDir, { recursive: true });
  // remove stale generated entries
  for (const f of ['index.ts']) if (existsSync(join(srcDir, f))) rmSync(join(srcDir, f));
  const indexLines = ['// Generated by @artui/wrapper-entries — do not edit.'];
  for (const tag of tags) {
    const from = framework === 'react' ? `./components/${tag}.js` : `./components/index.js`;
    const line = `export { ${pascal(tag)} as ${unprefixed(tag)} } from '${from}';`;
    indexLines.push(line);
    writeFileSync(join(srcDir, `${slug(tag)}.ts`), `// Generated by @artui/wrapper-entries — do not edit.\n${line}\n`);
    exportsMap[`./${slug(tag)}`] = { types: `./dist/${slug(tag)}.d.ts`, import: `./dist/${slug(tag)}.js` };
  }
  if (framework === 'react') indexLines.push(`export type { StencilReactComponent } from '@stencil/react-output-target/runtime';`);
  writeFileSync(join(srcDir, 'index.ts'), indexLines.join('\n') + '\n');
  if (framework === 'react') {
    // `@aranghat/<tier>-react/next` — server wrappers for React Server Components (Next.js App
    // Router, ADR-0023): they render through the tier's hydrate module, then hand over to the client.
    const serverLines = ['// Generated by @artui/wrapper-entries — do not edit. Server-component entry (ADR-0023).'];
    for (const tag of tags) serverLines.push(`export { ${pascal(tag)} as ${unprefixed(tag)} } from './components/${tag}.server.js';`);
    writeFileSync(join(srcDir, 'next.ts'), serverLines.join('\n') + '\n');
    exportsMap['./next'] = { types: './dist/next.d.ts', import: './dist/next.js' };
  }
} else if (framework === 'angular') {
  const srcDir = join(pkgDir, 'src');
  mkdirSync(srcDir, { recursive: true });
  const accessors = existsSync(join(srcDir, 'directives')) ? readdirSync(join(srcDir, 'directives')).filter((f) => /-value-accessor\.ts$/.test(f)).map((f) => `export * from './directives/${f.replace(/\.ts$/, '')}';`) : [];
  writeFileSync(join(srcDir, 'public-api.ts'), `// Generated by @artui/wrapper-entries — do not edit.\nexport * from './directives/proxies';\nexport { DIRECTIVES } from './directives/index';\n${accessors.join('\n')}${accessors.length ? '\n' : ''}`);
  // Angular libraries are consumed through the single entry (ng-packagr secondary entries are a Phase 8 refinement).
} else if (framework === 'core') {
  // `artui-ssr` (ADR-0023): the client that adopts server-rendered shadow roots, built from the
  // same sources into dist/components-ssr; a bundler opts in with that resolve condition.
  const entry = (file, types) => ({ types, 'artui-ssr': file.replace('./dist/components/', './dist/components-ssr/'), import: file });
  exportsMap['.'] = entry('./dist/components/index.js', './dist/types/index.d.ts');
  exportsMap['./dist/components'] = entry('./dist/components/index.js', './dist/components/index.d.ts');
  exportsMap['./dist/components/*'] = { types: './dist/components/*', 'artui-ssr': './dist/components-ssr/*', default: './dist/components/*' };
  for (const tag of tags) {
    exportsMap[`./${slug(tag)}`] = entry(`./dist/components/${tag}.js`, `./dist/components/${tag}.d.ts`);
  }
  exportsMap['./docs.json'] = './dist/docs.json';
}

exportsMap['./package.json'] = './package.json';
if (framework !== 'angular') pkg.exports = exportsMap; // ng-packagr owns the Angular exports map
if (framework === 'core') pkg.types = './dist/types/index.d.ts';
writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
console.log(`✔ ${pkg.name}: ${tags.length} component entr${tags.length === 1 ? 'y' : 'ies'}`);
