import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ArtButton, ArtRadio, ArtRadioGroup, SelectValueAccessor } from '@aranghat/base-angular';

@Component({
  selector: 'sample-radio-group-form',
  // SelectValueAccessor bridges art-radio-group to ngModel / reactive forms (generated by the Angular output target)
  imports: [FormsModule, ArtButton, ArtRadio, ArtRadioGroup, SelectValueAccessor],
  template: `
    <form (submit)="onSubmit($event)">
      <art-radio-group name="notify" required aria-label="Notify me about" [(ngModel)]="notify">
        <art-radio value="all">All new messages</art-radio>
        <art-radio value="mentions">Direct messages and mentions</art-radio>
        <art-radio value="none">Nothing</art-radio>
      </art-radio-group>
      <art-button type="submit">Submit</art-button>
    </form>
  `,
})
export class RadioGroupForm {
  notify = '';
  onSubmit(e: Event) {
    e.preventDefault();
    console.log('submitted', Object.fromEntries(new FormData(e.target as HTMLFormElement)), this.notify);
  }
}
