/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Phase 0 proof overlay. Consumes `<art-hello>` from `@aranghat/base` to prove
     * cross-tier composition: base is a peer dependency, never bundled (ADR-0002).
     * Removed when Dialog lands.
     */
    interface ArtHelloOverlay {
        /**
          * Passed through to the inner `<art-hello>`.
          * @default 'World'
         */
        "name": string;
        /**
          * Whether the overlay is shown.
          * @default false
         */
        "open": boolean;
    }
}
export interface ArtHelloOverlayCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtHelloOverlayElement;
}
declare global {
    interface HTMLArtHelloOverlayElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Phase 0 proof overlay. Consumes `<art-hello>` from `@aranghat/base` to prove
     * cross-tier composition: base is a peer dependency, never bundled (ADR-0002).
     * Removed when Dialog lands.
     */
    interface HTMLArtHelloOverlayElement extends Components.ArtHelloOverlay, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtHelloOverlayElementEventMap>(type: K, listener: (this: HTMLArtHelloOverlayElement, ev: ArtHelloOverlayCustomEvent<HTMLArtHelloOverlayElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtHelloOverlayElementEventMap>(type: K, listener: (this: HTMLArtHelloOverlayElement, ev: ArtHelloOverlayCustomEvent<HTMLArtHelloOverlayElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtHelloOverlayElement: {
        prototype: HTMLArtHelloOverlayElement;
        new (): HTMLArtHelloOverlayElement;
    };
    interface HTMLElementTagNameMap {
        "art-hello-overlay": HTMLArtHelloOverlayElement;
    }
}
declare namespace LocalJSX {
    /**
     * Phase 0 proof overlay. Consumes `<art-hello>` from `@aranghat/base` to prove
     * cross-tier composition: base is a peer dependency, never bundled (ADR-0002).
     * Removed when Dialog lands.
     */
    interface ArtHelloOverlay {
        /**
          * Passed through to the inner `<art-hello>`.
          * @default 'World'
         */
        "name"?: string;
        /**
          * Emitted when `open` changes because of user interaction (Escape / close button).
         */
        "onOpen-change"?: (event: ArtHelloOverlayCustomEvent<{ open: boolean }>) => void;
        /**
          * Whether the overlay is shown.
          * @default false
         */
        "open"?: boolean;
    }

    interface ArtHelloOverlayAttributes {
        "open": boolean;
        "name": string;
    }

    interface IntrinsicElements {
        "art-hello-overlay": Omit<ArtHelloOverlay, keyof ArtHelloOverlayAttributes> & { [K in keyof ArtHelloOverlay & keyof ArtHelloOverlayAttributes]?: ArtHelloOverlay[K] } & { [K in keyof ArtHelloOverlay & keyof ArtHelloOverlayAttributes as `attr:${K}`]?: ArtHelloOverlayAttributes[K] } & { [K in keyof ArtHelloOverlay & keyof ArtHelloOverlayAttributes as `prop:${K}`]?: ArtHelloOverlay[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Phase 0 proof overlay. Consumes `<art-hello>` from `@aranghat/base` to prove
             * cross-tier composition: base is a peer dependency, never bundled (ADR-0002).
             * Removed when Dialog lands.
             */
            "art-hello-overlay": LocalJSX.IntrinsicElements["art-hello-overlay"] & JSXBase.HTMLAttributes<HTMLArtHelloOverlayElement>;
        }
    }
}
