// Public surface of @aranghat/modals. components.d.ts is generated by Stencil (never edit).
export * from './components';
// Common Dialogs — the imperative `confirm()`, `alert()` and `prompt()` that resolve promises: `import { confirm } from '@aranghat/modals'`.
export { alert, confirm, prompt } from './common-dialogs/common-dialogs';
export type { CommonDialogOptions, PromptOptions } from './common-dialogs/common-dialogs';
