/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Placement } from "@aranghat/primitives/floating";
export { Placement } from "@aranghat/primitives/floating";
export namespace Components {
    /**
     * Breadcrumb — shadcn/ui parity. A `<nav aria-label="breadcrumb">` with an ordered list of
     * `<art-breadcrumb-item>`s; every item but the last is followed by a separator, the last
     * one (`current`) names the page.
     */
    interface ArtBreadcrumb {
        /**
          * Accessible name of the landmark.
          * @default 'breadcrumb'
         */
        "label": string;
        /**
          * Separator glyph between items.
          * @default 'chevron'
         */
        "separator": 'chevron' | 'slash';
    }
    /**
     * Breadcrumb Item — one step of an `<art-breadcrumb>`: a link (`<a>` in the default slot),
     * the current page (`current`), or an ellipsis for collapsed steps. The separator after it
     * is drawn here so the list stays a plain sequence of items.
     */
    interface ArtBreadcrumbItem {
        /**
          * The page being viewed: rendered as text with `aria-current="page"`.
          * @default false
         */
        "current": boolean;
        /**
          * Stands for collapsed steps ("…"); put a menu around it for the hidden pages.
          * @default false
         */
        "ellipsis": boolean;
    }
    /**
     * Dropdown Menu — shadcn/ui parity. A menu of actions opened from a trigger, on the platform
     * top layer: items, checkbox and radio items, labels, groups, separators, shortcuts and
     * submenus. Arrow keys move, typing jumps, Enter / Space activate, Escape closes and returns
     * focus to the trigger.
     */
    interface ArtDropdownMenu {
        /**
          * Accessible name of the menu; defaults to the trigger's text.
         */
        "label"?: string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * Preferred side / alignment of the panel.
          * @default 'bottom-start'
         */
        "placement": Placement;
    }
    /**
     * Dropdown Menu Group — groups items under an accessible name.
     */
    interface ArtDropdownMenuGroup {
        "label"?: string;
    }
    /**
     * Dropdown Menu Item — an action (`type="item"`), a toggle (`type="checkbox"`) or a choice
     * (`type="radio"`, inside `art-dropdown-menu-radio-group`); with `href` it is a link.
     * Emits `select` when activated (cancelable: `preventDefault()` keeps the menu open); checkbox
     * and radio items also emit `change`.
     */
    interface ArtDropdownMenuItem {
        /**
          * Checkbox / radio state.
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * Renders the item as a link.
         */
        "href"?: string;
        /**
          * Indent to align with checkbox / radio items.
          * @default false
         */
        "inset": boolean;
        "target"?: string;
        /**
          * @default 'item'
         */
        "type": 'item' | 'checkbox' | 'radio';
        /**
          * Value reported by `select` / `change` (radio items need one).
          * @default ''
         */
        "value": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'destructive';
    }
    /**
     * Dropdown Menu Label — a heading for a run of items.
     */
    interface ArtDropdownMenuLabel {
        /**
          * Indent to align with checkbox / radio items.
          * @default false
         */
        "inset": boolean;
    }
    /**
     * Dropdown Menu Radio Group — keeps one `type="radio"` item checked and reports its value.
     */
    interface ArtDropdownMenuRadioGroup {
        /**
          * Value of the checked item.
          * @default ''
         */
        "value": string;
    }
    /**
     * Dropdown Menu Separator — a rule between runs of items.
     */
    interface ArtDropdownMenuSeparator {
    }
    /**
     * Dropdown Menu Sub — a submenu: an item in the `trigger` slot opens a nested `role="menu"`
     * beside it on hover, ArrowRight, Enter or Space; ArrowLeft or Escape closes it and returns
     * to the trigger.
     */
    interface ArtDropdownMenuSub {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * Open and focus the first item (keyboard).
         */
        "openSub": () => Promise<void>;
    }
    /**
     * Pagination — shadcn/ui parity. Previous / next, page numbers around the current page with
     * ellipses, the active page as an outline button. Buttons by default (`page-change`), links
     * with `href-template` (`?page={page}`) for crawlable pages.
     */
    interface ArtPagination {
        /**
          * Pages always shown at the start and end.
          * @default 1
         */
        "boundaries": number;
        /**
          * Render links instead of buttons: `{page}` is replaced (e.g. `?page={page}`).
         */
        "hrefTemplate"?: string;
        /**
          * Accessible name of the landmark.
          * @default 'pagination'
         */
        "label": string;
        /**
          * @default 'Next'
         */
        "nextLabel": string;
        /**
          * Current page, 1-based.
          * @default 1
         */
        "page": number;
        /**
          * @default 'Previous'
         */
        "previousLabel": string;
        /**
          * Pages shown on each side of the current one.
          * @default 1
         */
        "siblings": number;
        /**
          * Number of pages.
          * @default 1
         */
        "total": number;
    }
}
export interface ArtDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtDropdownMenuElement;
}
export interface ArtDropdownMenuItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtDropdownMenuItemElement;
}
export interface ArtDropdownMenuRadioGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtDropdownMenuRadioGroupElement;
}
export interface ArtDropdownMenuSubCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtDropdownMenuSubElement;
}
export interface ArtPaginationCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtPaginationElement;
}
declare global {
    /**
     * Breadcrumb — shadcn/ui parity. A `<nav aria-label="breadcrumb">` with an ordered list of
     * `<art-breadcrumb-item>`s; every item but the last is followed by a separator, the last
     * one (`current`) names the page.
     */
    interface HTMLArtBreadcrumbElement extends Components.ArtBreadcrumb, HTMLStencilElement {
    }
    var HTMLArtBreadcrumbElement: {
        prototype: HTMLArtBreadcrumbElement;
        new (): HTMLArtBreadcrumbElement;
    };
    /**
     * Breadcrumb Item — one step of an `<art-breadcrumb>`: a link (`<a>` in the default slot),
     * the current page (`current`), or an ellipsis for collapsed steps. The separator after it
     * is drawn here so the list stays a plain sequence of items.
     */
    interface HTMLArtBreadcrumbItemElement extends Components.ArtBreadcrumbItem, HTMLStencilElement {
    }
    var HTMLArtBreadcrumbItemElement: {
        prototype: HTMLArtBreadcrumbItemElement;
        new (): HTMLArtBreadcrumbItemElement;
    };
    interface HTMLArtDropdownMenuElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Dropdown Menu — shadcn/ui parity. A menu of actions opened from a trigger, on the platform
     * top layer: items, checkbox and radio items, labels, groups, separators, shortcuts and
     * submenus. Arrow keys move, typing jumps, Enter / Space activate, Escape closes and returns
     * focus to the trigger.
     */
    interface HTMLArtDropdownMenuElement extends Components.ArtDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtDropdownMenuElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuElement, ev: ArtDropdownMenuCustomEvent<HTMLArtDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtDropdownMenuElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuElement, ev: ArtDropdownMenuCustomEvent<HTMLArtDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtDropdownMenuElement: {
        prototype: HTMLArtDropdownMenuElement;
        new (): HTMLArtDropdownMenuElement;
    };
    /**
     * Dropdown Menu Group — groups items under an accessible name.
     */
    interface HTMLArtDropdownMenuGroupElement extends Components.ArtDropdownMenuGroup, HTMLStencilElement {
    }
    var HTMLArtDropdownMenuGroupElement: {
        prototype: HTMLArtDropdownMenuGroupElement;
        new (): HTMLArtDropdownMenuGroupElement;
    };
    interface HTMLArtDropdownMenuItemElementEventMap {
        "select": { value: string; checked?: boolean };
        "change": { value: string; checked: boolean };
    }
    /**
     * Dropdown Menu Item — an action (`type="item"`), a toggle (`type="checkbox"`) or a choice
     * (`type="radio"`, inside `art-dropdown-menu-radio-group`); with `href` it is a link.
     * Emits `select` when activated (cancelable: `preventDefault()` keeps the menu open); checkbox
     * and radio items also emit `change`.
     */
    interface HTMLArtDropdownMenuItemElement extends Components.ArtDropdownMenuItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtDropdownMenuItemElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuItemElement, ev: ArtDropdownMenuItemCustomEvent<HTMLArtDropdownMenuItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtDropdownMenuItemElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuItemElement, ev: ArtDropdownMenuItemCustomEvent<HTMLArtDropdownMenuItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtDropdownMenuItemElement: {
        prototype: HTMLArtDropdownMenuItemElement;
        new (): HTMLArtDropdownMenuItemElement;
    };
    /**
     * Dropdown Menu Label — a heading for a run of items.
     */
    interface HTMLArtDropdownMenuLabelElement extends Components.ArtDropdownMenuLabel, HTMLStencilElement {
    }
    var HTMLArtDropdownMenuLabelElement: {
        prototype: HTMLArtDropdownMenuLabelElement;
        new (): HTMLArtDropdownMenuLabelElement;
    };
    interface HTMLArtDropdownMenuRadioGroupElementEventMap {
        "value-change": { value: string };
    }
    /**
     * Dropdown Menu Radio Group — keeps one `type="radio"` item checked and reports its value.
     */
    interface HTMLArtDropdownMenuRadioGroupElement extends Components.ArtDropdownMenuRadioGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtDropdownMenuRadioGroupElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuRadioGroupElement, ev: ArtDropdownMenuRadioGroupCustomEvent<HTMLArtDropdownMenuRadioGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtDropdownMenuRadioGroupElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuRadioGroupElement, ev: ArtDropdownMenuRadioGroupCustomEvent<HTMLArtDropdownMenuRadioGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtDropdownMenuRadioGroupElement: {
        prototype: HTMLArtDropdownMenuRadioGroupElement;
        new (): HTMLArtDropdownMenuRadioGroupElement;
    };
    /**
     * Dropdown Menu Separator — a rule between runs of items.
     */
    interface HTMLArtDropdownMenuSeparatorElement extends Components.ArtDropdownMenuSeparator, HTMLStencilElement {
    }
    var HTMLArtDropdownMenuSeparatorElement: {
        prototype: HTMLArtDropdownMenuSeparatorElement;
        new (): HTMLArtDropdownMenuSeparatorElement;
    };
    interface HTMLArtDropdownMenuSubElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Dropdown Menu Sub — a submenu: an item in the `trigger` slot opens a nested `role="menu"`
     * beside it on hover, ArrowRight, Enter or Space; ArrowLeft or Escape closes it and returns
     * to the trigger.
     */
    interface HTMLArtDropdownMenuSubElement extends Components.ArtDropdownMenuSub, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtDropdownMenuSubElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuSubElement, ev: ArtDropdownMenuSubCustomEvent<HTMLArtDropdownMenuSubElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtDropdownMenuSubElementEventMap>(type: K, listener: (this: HTMLArtDropdownMenuSubElement, ev: ArtDropdownMenuSubCustomEvent<HTMLArtDropdownMenuSubElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtDropdownMenuSubElement: {
        prototype: HTMLArtDropdownMenuSubElement;
        new (): HTMLArtDropdownMenuSubElement;
    };
    interface HTMLArtPaginationElementEventMap {
        "page-change": { page: number };
    }
    /**
     * Pagination — shadcn/ui parity. Previous / next, page numbers around the current page with
     * ellipses, the active page as an outline button. Buttons by default (`page-change`), links
     * with `href-template` (`?page={page}`) for crawlable pages.
     */
    interface HTMLArtPaginationElement extends Components.ArtPagination, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtPaginationElementEventMap>(type: K, listener: (this: HTMLArtPaginationElement, ev: ArtPaginationCustomEvent<HTMLArtPaginationElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtPaginationElementEventMap>(type: K, listener: (this: HTMLArtPaginationElement, ev: ArtPaginationCustomEvent<HTMLArtPaginationElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtPaginationElement: {
        prototype: HTMLArtPaginationElement;
        new (): HTMLArtPaginationElement;
    };
    interface HTMLElementTagNameMap {
        "art-breadcrumb": HTMLArtBreadcrumbElement;
        "art-breadcrumb-item": HTMLArtBreadcrumbItemElement;
        "art-dropdown-menu": HTMLArtDropdownMenuElement;
        "art-dropdown-menu-group": HTMLArtDropdownMenuGroupElement;
        "art-dropdown-menu-item": HTMLArtDropdownMenuItemElement;
        "art-dropdown-menu-label": HTMLArtDropdownMenuLabelElement;
        "art-dropdown-menu-radio-group": HTMLArtDropdownMenuRadioGroupElement;
        "art-dropdown-menu-separator": HTMLArtDropdownMenuSeparatorElement;
        "art-dropdown-menu-sub": HTMLArtDropdownMenuSubElement;
        "art-pagination": HTMLArtPaginationElement;
    }
}
declare namespace LocalJSX {
    /**
     * Breadcrumb — shadcn/ui parity. A `<nav aria-label="breadcrumb">` with an ordered list of
     * `<art-breadcrumb-item>`s; every item but the last is followed by a separator, the last
     * one (`current`) names the page.
     */
    interface ArtBreadcrumb {
        /**
          * Accessible name of the landmark.
          * @default 'breadcrumb'
         */
        "label"?: string;
        /**
          * Separator glyph between items.
          * @default 'chevron'
         */
        "separator"?: 'chevron' | 'slash';
    }
    /**
     * Breadcrumb Item — one step of an `<art-breadcrumb>`: a link (`<a>` in the default slot),
     * the current page (`current`), or an ellipsis for collapsed steps. The separator after it
     * is drawn here so the list stays a plain sequence of items.
     */
    interface ArtBreadcrumbItem {
        /**
          * The page being viewed: rendered as text with `aria-current="page"`.
          * @default false
         */
        "current"?: boolean;
        /**
          * Stands for collapsed steps ("…"); put a menu around it for the hidden pages.
          * @default false
         */
        "ellipsis"?: boolean;
    }
    /**
     * Dropdown Menu — shadcn/ui parity. A menu of actions opened from a trigger, on the platform
     * top layer: items, checkbox and radio items, labels, groups, separators, shortcuts and
     * submenus. Arrow keys move, typing jumps, Enter / Space activate, Escape closes and returns
     * focus to the trigger.
     */
    interface ArtDropdownMenu {
        /**
          * Accessible name of the menu; defaults to the trigger's text.
         */
        "label"?: string;
        "onOpen-change"?: (event: ArtDropdownMenuCustomEvent<{ open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * Preferred side / alignment of the panel.
          * @default 'bottom-start'
         */
        "placement"?: Placement;
    }
    /**
     * Dropdown Menu Group — groups items under an accessible name.
     */
    interface ArtDropdownMenuGroup {
        "label"?: string;
    }
    /**
     * Dropdown Menu Item — an action (`type="item"`), a toggle (`type="checkbox"`) or a choice
     * (`type="radio"`, inside `art-dropdown-menu-radio-group`); with `href` it is a link.
     * Emits `select` when activated (cancelable: `preventDefault()` keeps the menu open); checkbox
     * and radio items also emit `change`.
     */
    interface ArtDropdownMenuItem {
        /**
          * Checkbox / radio state.
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Renders the item as a link.
         */
        "href"?: string;
        /**
          * Indent to align with checkbox / radio items.
          * @default false
         */
        "inset"?: boolean;
        /**
          * Checkbox / radio state changed; `detail.checked`, `detail.value`.
         */
        "onChange"?: (event: ArtDropdownMenuItemCustomEvent<{ value: string; checked: boolean }>) => void;
        /**
          * Emitted when the item is activated; `detail.value`, `detail.checked`. Cancelable — `preventDefault()` keeps the menu open.
         */
        "onSelect"?: (event: ArtDropdownMenuItemCustomEvent<{ value: string; checked?: boolean }>) => void;
        "target"?: string;
        /**
          * @default 'item'
         */
        "type"?: 'item' | 'checkbox' | 'radio';
        /**
          * Value reported by `select` / `change` (radio items need one).
          * @default ''
         */
        "value"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'destructive';
    }
    /**
     * Dropdown Menu Label — a heading for a run of items.
     */
    interface ArtDropdownMenuLabel {
        /**
          * Indent to align with checkbox / radio items.
          * @default false
         */
        "inset"?: boolean;
    }
    /**
     * Dropdown Menu Radio Group — keeps one `type="radio"` item checked and reports its value.
     */
    interface ArtDropdownMenuRadioGroup {
        /**
          * Emitted when the checked item changes; `detail.value`.
         */
        "onValue-change"?: (event: ArtDropdownMenuRadioGroupCustomEvent<{ value: string }>) => void;
        /**
          * Value of the checked item.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Dropdown Menu Separator — a rule between runs of items.
     */
    interface ArtDropdownMenuSeparator {
    }
    /**
     * Dropdown Menu Sub — a submenu: an item in the `trigger` slot opens a nested `role="menu"`
     * beside it on hover, ArrowRight, Enter or Space; ArrowLeft or Escape closes it and returns
     * to the trigger.
     */
    interface ArtDropdownMenuSub {
        "onOpen-change"?: (event: ArtDropdownMenuSubCustomEvent<{ open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Pagination — shadcn/ui parity. Previous / next, page numbers around the current page with
     * ellipses, the active page as an outline button. Buttons by default (`page-change`), links
     * with `href-template` (`?page={page}`) for crawlable pages.
     */
    interface ArtPagination {
        /**
          * Pages always shown at the start and end.
          * @default 1
         */
        "boundaries"?: number;
        /**
          * Render links instead of buttons: `{page}` is replaced (e.g. `?page={page}`).
         */
        "hrefTemplate"?: string;
        /**
          * Accessible name of the landmark.
          * @default 'pagination'
         */
        "label"?: string;
        /**
          * @default 'Next'
         */
        "nextLabel"?: string;
        /**
          * Emitted when the user picks a page; `detail.page`.
         */
        "onPage-change"?: (event: ArtPaginationCustomEvent<{ page: number }>) => void;
        /**
          * Current page, 1-based.
          * @default 1
         */
        "page"?: number;
        /**
          * @default 'Previous'
         */
        "previousLabel"?: string;
        /**
          * Pages shown on each side of the current one.
          * @default 1
         */
        "siblings"?: number;
        /**
          * Number of pages.
          * @default 1
         */
        "total"?: number;
    }

    interface ArtBreadcrumbAttributes {
        "separator": 'chevron' | 'slash';
        "label": string;
    }
    interface ArtBreadcrumbItemAttributes {
        "current": boolean;
        "ellipsis": boolean;
    }
    interface ArtDropdownMenuAttributes {
        "open": boolean;
        "placement": Placement;
        "label": string;
    }
    interface ArtDropdownMenuGroupAttributes {
        "label": string;
    }
    interface ArtDropdownMenuItemAttributes {
        "type": 'item' | 'checkbox' | 'radio';
        "value": string;
        "checked": boolean;
        "disabled": boolean;
        "inset": boolean;
        "variant": 'default' | 'destructive';
        "href": string;
        "target": string;
    }
    interface ArtDropdownMenuLabelAttributes {
        "inset": boolean;
    }
    interface ArtDropdownMenuRadioGroupAttributes {
        "value": string;
    }
    interface ArtDropdownMenuSubAttributes {
        "open": boolean;
    }
    interface ArtPaginationAttributes {
        "page": number;
        "total": number;
        "siblings": number;
        "boundaries": number;
        "hrefTemplate": string;
        "label": string;
        "previousLabel": string;
        "nextLabel": string;
    }

    interface IntrinsicElements {
        "art-breadcrumb": Omit<ArtBreadcrumb, keyof ArtBreadcrumbAttributes> & { [K in keyof ArtBreadcrumb & keyof ArtBreadcrumbAttributes]?: ArtBreadcrumb[K] } & { [K in keyof ArtBreadcrumb & keyof ArtBreadcrumbAttributes as `attr:${K}`]?: ArtBreadcrumbAttributes[K] } & { [K in keyof ArtBreadcrumb & keyof ArtBreadcrumbAttributes as `prop:${K}`]?: ArtBreadcrumb[K] };
        "art-breadcrumb-item": Omit<ArtBreadcrumbItem, keyof ArtBreadcrumbItemAttributes> & { [K in keyof ArtBreadcrumbItem & keyof ArtBreadcrumbItemAttributes]?: ArtBreadcrumbItem[K] } & { [K in keyof ArtBreadcrumbItem & keyof ArtBreadcrumbItemAttributes as `attr:${K}`]?: ArtBreadcrumbItemAttributes[K] } & { [K in keyof ArtBreadcrumbItem & keyof ArtBreadcrumbItemAttributes as `prop:${K}`]?: ArtBreadcrumbItem[K] };
        "art-dropdown-menu": Omit<ArtDropdownMenu, keyof ArtDropdownMenuAttributes> & { [K in keyof ArtDropdownMenu & keyof ArtDropdownMenuAttributes]?: ArtDropdownMenu[K] } & { [K in keyof ArtDropdownMenu & keyof ArtDropdownMenuAttributes as `attr:${K}`]?: ArtDropdownMenuAttributes[K] } & { [K in keyof ArtDropdownMenu & keyof ArtDropdownMenuAttributes as `prop:${K}`]?: ArtDropdownMenu[K] };
        "art-dropdown-menu-group": Omit<ArtDropdownMenuGroup, keyof ArtDropdownMenuGroupAttributes> & { [K in keyof ArtDropdownMenuGroup & keyof ArtDropdownMenuGroupAttributes]?: ArtDropdownMenuGroup[K] } & { [K in keyof ArtDropdownMenuGroup & keyof ArtDropdownMenuGroupAttributes as `attr:${K}`]?: ArtDropdownMenuGroupAttributes[K] } & { [K in keyof ArtDropdownMenuGroup & keyof ArtDropdownMenuGroupAttributes as `prop:${K}`]?: ArtDropdownMenuGroup[K] };
        "art-dropdown-menu-item": Omit<ArtDropdownMenuItem, keyof ArtDropdownMenuItemAttributes> & { [K in keyof ArtDropdownMenuItem & keyof ArtDropdownMenuItemAttributes]?: ArtDropdownMenuItem[K] } & { [K in keyof ArtDropdownMenuItem & keyof ArtDropdownMenuItemAttributes as `attr:${K}`]?: ArtDropdownMenuItemAttributes[K] } & { [K in keyof ArtDropdownMenuItem & keyof ArtDropdownMenuItemAttributes as `prop:${K}`]?: ArtDropdownMenuItem[K] };
        "art-dropdown-menu-label": Omit<ArtDropdownMenuLabel, keyof ArtDropdownMenuLabelAttributes> & { [K in keyof ArtDropdownMenuLabel & keyof ArtDropdownMenuLabelAttributes]?: ArtDropdownMenuLabel[K] } & { [K in keyof ArtDropdownMenuLabel & keyof ArtDropdownMenuLabelAttributes as `attr:${K}`]?: ArtDropdownMenuLabelAttributes[K] } & { [K in keyof ArtDropdownMenuLabel & keyof ArtDropdownMenuLabelAttributes as `prop:${K}`]?: ArtDropdownMenuLabel[K] };
        "art-dropdown-menu-radio-group": Omit<ArtDropdownMenuRadioGroup, keyof ArtDropdownMenuRadioGroupAttributes> & { [K in keyof ArtDropdownMenuRadioGroup & keyof ArtDropdownMenuRadioGroupAttributes]?: ArtDropdownMenuRadioGroup[K] } & { [K in keyof ArtDropdownMenuRadioGroup & keyof ArtDropdownMenuRadioGroupAttributes as `attr:${K}`]?: ArtDropdownMenuRadioGroupAttributes[K] } & { [K in keyof ArtDropdownMenuRadioGroup & keyof ArtDropdownMenuRadioGroupAttributes as `prop:${K}`]?: ArtDropdownMenuRadioGroup[K] };
        "art-dropdown-menu-separator": ArtDropdownMenuSeparator;
        "art-dropdown-menu-sub": Omit<ArtDropdownMenuSub, keyof ArtDropdownMenuSubAttributes> & { [K in keyof ArtDropdownMenuSub & keyof ArtDropdownMenuSubAttributes]?: ArtDropdownMenuSub[K] } & { [K in keyof ArtDropdownMenuSub & keyof ArtDropdownMenuSubAttributes as `attr:${K}`]?: ArtDropdownMenuSubAttributes[K] } & { [K in keyof ArtDropdownMenuSub & keyof ArtDropdownMenuSubAttributes as `prop:${K}`]?: ArtDropdownMenuSub[K] };
        "art-pagination": Omit<ArtPagination, keyof ArtPaginationAttributes> & { [K in keyof ArtPagination & keyof ArtPaginationAttributes]?: ArtPagination[K] } & { [K in keyof ArtPagination & keyof ArtPaginationAttributes as `attr:${K}`]?: ArtPaginationAttributes[K] } & { [K in keyof ArtPagination & keyof ArtPaginationAttributes as `prop:${K}`]?: ArtPagination[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Breadcrumb — shadcn/ui parity. A `<nav aria-label="breadcrumb">` with an ordered list of
             * `<art-breadcrumb-item>`s; every item but the last is followed by a separator, the last
             * one (`current`) names the page.
             */
            "art-breadcrumb": LocalJSX.IntrinsicElements["art-breadcrumb"] & JSXBase.HTMLAttributes<HTMLArtBreadcrumbElement>;
            /**
             * Breadcrumb Item — one step of an `<art-breadcrumb>`: a link (`<a>` in the default slot),
             * the current page (`current`), or an ellipsis for collapsed steps. The separator after it
             * is drawn here so the list stays a plain sequence of items.
             */
            "art-breadcrumb-item": LocalJSX.IntrinsicElements["art-breadcrumb-item"] & JSXBase.HTMLAttributes<HTMLArtBreadcrumbItemElement>;
            /**
             * Dropdown Menu — shadcn/ui parity. A menu of actions opened from a trigger, on the platform
             * top layer: items, checkbox and radio items, labels, groups, separators, shortcuts and
             * submenus. Arrow keys move, typing jumps, Enter / Space activate, Escape closes and returns
             * focus to the trigger.
             */
            "art-dropdown-menu": LocalJSX.IntrinsicElements["art-dropdown-menu"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuElement>;
            /**
             * Dropdown Menu Group — groups items under an accessible name.
             */
            "art-dropdown-menu-group": LocalJSX.IntrinsicElements["art-dropdown-menu-group"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuGroupElement>;
            /**
             * Dropdown Menu Item — an action (`type="item"`), a toggle (`type="checkbox"`) or a choice
             * (`type="radio"`, inside `art-dropdown-menu-radio-group`); with `href` it is a link.
             * Emits `select` when activated (cancelable: `preventDefault()` keeps the menu open); checkbox
             * and radio items also emit `change`.
             */
            "art-dropdown-menu-item": LocalJSX.IntrinsicElements["art-dropdown-menu-item"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuItemElement>;
            /**
             * Dropdown Menu Label — a heading for a run of items.
             */
            "art-dropdown-menu-label": LocalJSX.IntrinsicElements["art-dropdown-menu-label"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuLabelElement>;
            /**
             * Dropdown Menu Radio Group — keeps one `type="radio"` item checked and reports its value.
             */
            "art-dropdown-menu-radio-group": LocalJSX.IntrinsicElements["art-dropdown-menu-radio-group"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuRadioGroupElement>;
            /**
             * Dropdown Menu Separator — a rule between runs of items.
             */
            "art-dropdown-menu-separator": LocalJSX.IntrinsicElements["art-dropdown-menu-separator"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuSeparatorElement>;
            /**
             * Dropdown Menu Sub — a submenu: an item in the `trigger` slot opens a nested `role="menu"`
             * beside it on hover, ArrowRight, Enter or Space; ArrowLeft or Escape closes it and returns
             * to the trigger.
             */
            "art-dropdown-menu-sub": LocalJSX.IntrinsicElements["art-dropdown-menu-sub"] & JSXBase.HTMLAttributes<HTMLArtDropdownMenuSubElement>;
            /**
             * Pagination — shadcn/ui parity. Previous / next, page numbers around the current page with
             * ellipses, the active page as an outline button. Buttons by default (`page-change`), links
             * with `href-template` (`?page={page}`) for crawlable pages.
             */
            "art-pagination": LocalJSX.IntrinsicElements["art-pagination"] & JSXBase.HTMLAttributes<HTMLArtPaginationElement>;
        }
    }
}
