/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconData } from "@aranghat/icons";
export { IconData } from "@aranghat/icons";
export namespace Components {
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface ArtHello {
        /**
          * Disabled state.
          * @default false
         */
        "disabled": boolean;
        /**
          * Who to greet.
          * @default 'World'
         */
        "name": string;
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant": 'default' | 'outline';
    }
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface ArtIcon {
        /**
          * Icon data imported from `@aranghat/icons/<name>`.
         */
        "icon"?: IconData;
        /**
          * Accessible label. When omitted the icon is decorative (`aria-hidden`).
         */
        "label"?: string;
        /**
          * Visual size; matches the control size scale.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
}
export interface ArtHelloCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtHelloElement;
}
declare global {
    interface HTMLArtHelloElementEventMap {
        "greet": { name: string };
    }
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface HTMLArtHelloElement extends Components.ArtHello, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtHelloElementEventMap>(type: K, listener: (this: HTMLArtHelloElement, ev: ArtHelloCustomEvent<HTMLArtHelloElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtHelloElementEventMap>(type: K, listener: (this: HTMLArtHelloElement, ev: ArtHelloCustomEvent<HTMLArtHelloElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtHelloElement: {
        prototype: HTMLArtHelloElement;
        new (): HTMLArtHelloElement;
    };
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface HTMLArtIconElement extends Components.ArtIcon, HTMLStencilElement {
    }
    var HTMLArtIconElement: {
        prototype: HTMLArtIconElement;
        new (): HTMLArtIconElement;
    };
    interface HTMLElementTagNameMap {
        "art-hello": HTMLArtHelloElement;
        "art-icon": HTMLArtIconElement;
    }
}
declare namespace LocalJSX {
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface ArtHello {
        /**
          * Disabled state.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Who to greet.
          * @default 'World'
         */
        "name"?: string;
        /**
          * Emitted after the greet button is activated.
         */
        "onGreet"?: (event: ArtHelloCustomEvent<{ name: string }>) => void;
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant"?: 'default' | 'outline';
    }
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface ArtIcon {
        /**
          * Icon data imported from `@aranghat/icons/<name>`.
         */
        "icon"?: IconData;
        /**
          * Accessible label. When omitted the icon is decorative (`aria-hidden`).
         */
        "label"?: string;
        /**
          * Visual size; matches the control size scale.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }

    interface ArtHelloAttributes {
        "name": string;
        "variant": 'default' | 'outline';
        "disabled": boolean;
    }
    interface ArtIconAttributes {
        "size": 'sm' | 'md' | 'lg';
        "label": string;
    }

    interface IntrinsicElements {
        "art-hello": Omit<ArtHello, keyof ArtHelloAttributes> & { [K in keyof ArtHello & keyof ArtHelloAttributes]?: ArtHello[K] } & { [K in keyof ArtHello & keyof ArtHelloAttributes as `attr:${K}`]?: ArtHelloAttributes[K] } & { [K in keyof ArtHello & keyof ArtHelloAttributes as `prop:${K}`]?: ArtHello[K] };
        "art-icon": Omit<ArtIcon, keyof ArtIconAttributes> & { [K in keyof ArtIcon & keyof ArtIconAttributes]?: ArtIcon[K] } & { [K in keyof ArtIcon & keyof ArtIconAttributes as `attr:${K}`]?: ArtIconAttributes[K] } & { [K in keyof ArtIcon & keyof ArtIconAttributes as `prop:${K}`]?: ArtIcon[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
             * recipe, a native `click` passing through and a kebab-case custom event.
             * Removed when Button lands.
             */
            "art-hello": LocalJSX.IntrinsicElements["art-hello"] & JSXBase.HTMLAttributes<HTMLArtHelloElement>;
            /**
             * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
             * into components: import the icon module you need and pass it as `icon`.
             */
            "art-icon": LocalJSX.IntrinsicElements["art-icon"] & JSXBase.HTMLAttributes<HTMLArtIconElement>;
        }
    }
}
