/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconData } from "@aranghat/icons";
export { IconData } from "@aranghat/icons";
export namespace Components {
    /**
     * Button — shadcn/ui parity (ADR-0012): variants `default | secondary | outline | ghost |
     * destructive | link`, sizes `sm | md | lg`, square `icon` buttons, `loading`, and `href`
     * rendering an anchor. Wraps a native `<button>` so `click` stays native (CLAUDE.md §3a);
     * form-associated so `type="submit"` / `type="reset"` work inside a plain `<form>`.
     */
    interface ArtButton {
        /**
          * Disabled: no interaction, no events.
          * @default false
         */
        "disabled": boolean;
        /**
          * `aria-label` set on the host moves onto the inner control: the focusable element lives in the shadow root and must carry the accessible name (axe `button-name`), and a generic host must not keep it (axe `aria-prohibited-attr`). Bound as a prop so framework re-renders that re-apply the attribute are picked up.
         */
        "hostAriaLabel"?: string | null;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * Square icon-only button. Provide an accessible name via `aria-label` on the host.
          * @default false
         */
        "icon": boolean;
        /**
          * Loading: shows a spinner in place of `start`, sets `aria-busy`, blocks activation.
          * @default false
         */
        "loading": boolean;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Control size; aligns with Input, Select and Combobox.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
        /**
          * Native button type. `submit` / `reset` act on the surrounding `<form>`.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant": 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link';
    }
    /**
     * Checkbox — shadcn/ui parity. A `role="checkbox"` button with checked / indeterminate states,
     * form-associated (submits `value` when checked). `change` is emitted from the host with
     * `detail.checked`; Vue `v-model:checked`, Angular `ngModel` (boolean) work out of the box.
     */
    interface ArtCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * Mixed state (e.g. "select all" with a partial selection). Cleared by the next toggle.
          * @default false
         */
        "indeterminate": boolean;
        /**
          * @default false
         */
        "invalid": boolean;
        "name"?: string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Submitted with the form when checked.
          * @default 'on'
         */
        "value": string;
    }
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface ArtHello {
        /**
          * Disabled state.
          * @default false
         */
        "disabled": boolean;
        /**
          * Who to greet.
          * @default 'World'
         */
        "name": string;
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant": 'default' | 'outline';
    }
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface ArtIcon {
        /**
          * Icon data imported from `@aranghat/icons/<name>`.
         */
        "icon"?: IconData;
        /**
          * Accessible label. When omitted the icon is decorative (`aria-hidden`).
         */
        "label"?: string;
        /**
          * Visual size; matches the control size scale.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
    }
    /**
     * Input — shadcn/ui parity. Wraps a native `<input>`; form-associated (FormData, validation,
     * reset); `input` / `change` are emitted from the host in response to the native events with
     * `event.target` being `<art-input>` and `detail.value` mirroring `target.value` (§3a). Sizes
     * share the control-height tokens so inputs align with buttons.
     */
    interface ArtInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        "inputmode"?: string;
        /**
          * Marks the field invalid (`aria-invalid` + destructive ring). Field sets it from validation.
          * @default false
         */
        "invalid": boolean;
        "max"?: string | number;
        "maxlength"?: number;
        "min"?: string | number;
        "minlength"?: number;
        /**
          * Form field name (submitted with the value).
         */
        "name"?: string;
        "pattern"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * Select all text.
         */
        "select": () => Promise<void>;
        /**
          * Focus the native input.
         */
        "setFocus": () => Promise<void>;
        /**
          * Control size; aligns with Button.
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        "step"?: string | number;
        /**
          * Native input type.
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url' | 'date' | 'time' | 'file';
        /**
          * Current value.
          * @default ''
         */
        "value": string;
    }
    /**
     * Label — shadcn/ui parity. A styled `<label>` for any control. Because shadow roots scope
     * ids, `for` is resolved at click time: activating the label focuses the target control
     * (or toggles it for checkbox-like controls), matching native label behaviour across tiers.
     */
    interface ArtLabel {
        /**
          * Dimmed and inert; Field sets this when its control is disabled.
          * @default false
         */
        "disabled": boolean;
        /**
          * id of the control this label describes (looked up in the label's own DOM tree, then the document). Attribute: `for`.
         */
        "htmlFor"?: string;
    }
    /**
     * Switch — shadcn/ui parity. A `role="switch"` toggle, form-associated (submits `value` when on).
     * `change` is emitted from the host with `detail.checked`.
     */
    interface ArtSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * @default false
         */
        "invalid": boolean;
        "name"?: string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'on'
         */
        "value": string;
    }
    /**
     * Textarea — shadcn/ui parity. Multi-line text field; grows with content (`field-sizing: content`),
     * form-associated, `input` / `change` emitted from the host with `detail.value` (§3a).
     */
    interface ArtTextarea {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled": boolean;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * @default false
         */
        "invalid": boolean;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly": boolean;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * Initial visible rows; the field still grows with content.
         */
        "rows"?: number;
        "setFocus": () => Promise<void>;
        /**
          * Density; changes inline padding only (height follows content).
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value": string;
    }
}
export interface ArtCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtCheckboxElement;
}
export interface ArtHelloCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtHelloElement;
}
export interface ArtInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtInputElement;
}
export interface ArtSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtSwitchElement;
}
export interface ArtTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtTextareaElement;
}
declare global {
    /**
     * Button — shadcn/ui parity (ADR-0012): variants `default | secondary | outline | ghost |
     * destructive | link`, sizes `sm | md | lg`, square `icon` buttons, `loading`, and `href`
     * rendering an anchor. Wraps a native `<button>` so `click` stays native (CLAUDE.md §3a);
     * form-associated so `type="submit"` / `type="reset"` work inside a plain `<form>`.
     */
    interface HTMLArtButtonElement extends Components.ArtButton, HTMLStencilElement {
    }
    var HTMLArtButtonElement: {
        prototype: HTMLArtButtonElement;
        new (): HTMLArtButtonElement;
    };
    interface HTMLArtCheckboxElementEventMap {
        "change": { checked: boolean };
    }
    /**
     * Checkbox — shadcn/ui parity. A `role="checkbox"` button with checked / indeterminate states,
     * form-associated (submits `value` when checked). `change` is emitted from the host with
     * `detail.checked`; Vue `v-model:checked`, Angular `ngModel` (boolean) work out of the box.
     */
    interface HTMLArtCheckboxElement extends Components.ArtCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtCheckboxElementEventMap>(type: K, listener: (this: HTMLArtCheckboxElement, ev: ArtCheckboxCustomEvent<HTMLArtCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtCheckboxElementEventMap>(type: K, listener: (this: HTMLArtCheckboxElement, ev: ArtCheckboxCustomEvent<HTMLArtCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtCheckboxElement: {
        prototype: HTMLArtCheckboxElement;
        new (): HTMLArtCheckboxElement;
    };
    interface HTMLArtHelloElementEventMap {
        "greet": { name: string };
    }
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface HTMLArtHelloElement extends Components.ArtHello, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtHelloElementEventMap>(type: K, listener: (this: HTMLArtHelloElement, ev: ArtHelloCustomEvent<HTMLArtHelloElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtHelloElementEventMap>(type: K, listener: (this: HTMLArtHelloElement, ev: ArtHelloCustomEvent<HTMLArtHelloElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtHelloElement: {
        prototype: HTMLArtHelloElement;
        new (): HTMLArtHelloElement;
    };
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface HTMLArtIconElement extends Components.ArtIcon, HTMLStencilElement {
    }
    var HTMLArtIconElement: {
        prototype: HTMLArtIconElement;
        new (): HTMLArtIconElement;
    };
    interface HTMLArtInputElementEventMap {
        "input": { value: string };
        "change": { value: string };
    }
    /**
     * Input — shadcn/ui parity. Wraps a native `<input>`; form-associated (FormData, validation,
     * reset); `input` / `change` are emitted from the host in response to the native events with
     * `event.target` being `<art-input>` and `detail.value` mirroring `target.value` (§3a). Sizes
     * share the control-height tokens so inputs align with buttons.
     */
    interface HTMLArtInputElement extends Components.ArtInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtInputElementEventMap>(type: K, listener: (this: HTMLArtInputElement, ev: ArtInputCustomEvent<HTMLArtInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtInputElementEventMap>(type: K, listener: (this: HTMLArtInputElement, ev: ArtInputCustomEvent<HTMLArtInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtInputElement: {
        prototype: HTMLArtInputElement;
        new (): HTMLArtInputElement;
    };
    /**
     * Label — shadcn/ui parity. A styled `<label>` for any control. Because shadow roots scope
     * ids, `for` is resolved at click time: activating the label focuses the target control
     * (or toggles it for checkbox-like controls), matching native label behaviour across tiers.
     */
    interface HTMLArtLabelElement extends Components.ArtLabel, HTMLStencilElement {
    }
    var HTMLArtLabelElement: {
        prototype: HTMLArtLabelElement;
        new (): HTMLArtLabelElement;
    };
    interface HTMLArtSwitchElementEventMap {
        "change": { checked: boolean };
    }
    /**
     * Switch — shadcn/ui parity. A `role="switch"` toggle, form-associated (submits `value` when on).
     * `change` is emitted from the host with `detail.checked`.
     */
    interface HTMLArtSwitchElement extends Components.ArtSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtSwitchElementEventMap>(type: K, listener: (this: HTMLArtSwitchElement, ev: ArtSwitchCustomEvent<HTMLArtSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtSwitchElementEventMap>(type: K, listener: (this: HTMLArtSwitchElement, ev: ArtSwitchCustomEvent<HTMLArtSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtSwitchElement: {
        prototype: HTMLArtSwitchElement;
        new (): HTMLArtSwitchElement;
    };
    interface HTMLArtTextareaElementEventMap {
        "input": { value: string };
        "change": { value: string };
    }
    /**
     * Textarea — shadcn/ui parity. Multi-line text field; grows with content (`field-sizing: content`),
     * form-associated, `input` / `change` emitted from the host with `detail.value` (§3a).
     */
    interface HTMLArtTextareaElement extends Components.ArtTextarea, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtTextareaElementEventMap>(type: K, listener: (this: HTMLArtTextareaElement, ev: ArtTextareaCustomEvent<HTMLArtTextareaElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtTextareaElementEventMap>(type: K, listener: (this: HTMLArtTextareaElement, ev: ArtTextareaCustomEvent<HTMLArtTextareaElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtTextareaElement: {
        prototype: HTMLArtTextareaElement;
        new (): HTMLArtTextareaElement;
    };
    interface HTMLElementTagNameMap {
        "art-button": HTMLArtButtonElement;
        "art-checkbox": HTMLArtCheckboxElement;
        "art-hello": HTMLArtHelloElement;
        "art-icon": HTMLArtIconElement;
        "art-input": HTMLArtInputElement;
        "art-label": HTMLArtLabelElement;
        "art-switch": HTMLArtSwitchElement;
        "art-textarea": HTMLArtTextareaElement;
    }
}
declare namespace LocalJSX {
    /**
     * Button — shadcn/ui parity (ADR-0012): variants `default | secondary | outline | ghost |
     * destructive | link`, sizes `sm | md | lg`, square `icon` buttons, `loading`, and `href`
     * rendering an anchor. Wraps a native `<button>` so `click` stays native (CLAUDE.md §3a);
     * form-associated so `type="submit"` / `type="reset"` work inside a plain `<form>`.
     */
    interface ArtButton {
        /**
          * Disabled: no interaction, no events.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        /**
          * `aria-label` set on the host moves onto the inner control: the focusable element lives in the shadow root and must carry the accessible name (axe `button-name`), and a generic host must not keep it (axe `aria-prohibited-attr`). Bound as a prop so framework re-renders that re-apply the attribute are picked up.
         */
        "hostAriaLabel"?: string | null;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * Square icon-only button. Provide an accessible name via `aria-label` on the host.
          * @default false
         */
        "icon"?: boolean;
        /**
          * Loading: shows a spinner in place of `start`, sets `aria-busy`, blocks activation.
          * @default false
         */
        "loading"?: boolean;
        /**
          * The name of the element, used when submitting an HTML form.
         */
        "name"?: string;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Control size; aligns with Input, Select and Combobox.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
        /**
          * Native button type. `submit` / `reset` act on the surrounding `<form>`.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant"?: 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link';
    }
    /**
     * Checkbox — shadcn/ui parity. A `role="checkbox"` button with checked / indeterminate states,
     * form-associated (submits `value` when checked). `change` is emitted from the host with
     * `detail.checked`; Vue `v-model:checked`, Angular `ngModel` (boolean) work out of the box.
     */
    interface ArtCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * Mixed state (e.g. "select all" with a partial selection). Cleared by the next toggle.
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "name"?: string;
        /**
          * Emitted after a user toggle; `detail.checked` mirrors `target.checked`.
         */
        "onChange"?: (event: ArtCheckboxCustomEvent<{ checked: boolean }>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Submitted with the form when checked.
          * @default 'on'
         */
        "value"?: string;
    }
    /**
     * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
     * recipe, a native `click` passing through and a kebab-case custom event.
     * Removed when Button lands.
     */
    interface ArtHello {
        /**
          * Disabled state.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Who to greet.
          * @default 'World'
         */
        "name"?: string;
        /**
          * Emitted after the greet button is activated.
         */
        "onGreet"?: (event: ArtHelloCustomEvent<{ name: string }>) => void;
        /**
          * Visual variant.
          * @default 'default'
         */
        "variant"?: 'default' | 'outline';
    }
    /**
     * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
     * into components: import the icon module you need and pass it as `icon`.
     */
    interface ArtIcon {
        /**
          * Icon data imported from `@aranghat/icons/<name>`.
         */
        "icon"?: IconData;
        /**
          * Accessible label. When omitted the icon is decorative (`aria-hidden`).
         */
        "label"?: string;
        /**
          * Visual size; matches the control size scale.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
    }
    /**
     * Input — shadcn/ui parity. Wraps a native `<input>`; form-associated (FormData, validation,
     * reset); `input` / `change` are emitted from the host in response to the native events with
     * `event.target` being `<art-input>` and `detail.value` mirroring `target.value` (§3a). Sizes
     * share the control-height tokens so inputs align with buttons.
     */
    interface ArtInput {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        "inputmode"?: string;
        /**
          * Marks the field invalid (`aria-invalid` + destructive ring). Field sets it from validation.
          * @default false
         */
        "invalid"?: boolean;
        "max"?: string | number;
        "maxlength"?: number;
        "min"?: string | number;
        "minlength"?: number;
        /**
          * Form field name (submitted with the value).
         */
        "name"?: string;
        /**
          * Emitted when the value is committed (blur / Enter).
         */
        "onChange"?: (event: ArtInputCustomEvent<{ value: string }>) => void;
        /**
          * Emitted on every keystroke; `detail.value` mirrors `target.value`. Kept native-named so `addEventListener('input')`, `onInput`, `@input` and `(input)` all work.
         */
        "onInput"?: (event: ArtInputCustomEvent<{ value: string }>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * Control size; aligns with Button.
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        "step"?: string | number;
        /**
          * Native input type.
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url' | 'date' | 'time' | 'file';
        /**
          * Current value.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Label — shadcn/ui parity. A styled `<label>` for any control. Because shadow roots scope
     * ids, `for` is resolved at click time: activating the label focuses the target control
     * (or toggles it for checkbox-like controls), matching native label behaviour across tiers.
     */
    interface ArtLabel {
        /**
          * Dimmed and inert; Field sets this when its control is disabled.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * id of the control this label describes (looked up in the label's own DOM tree, then the document). Attribute: `for`.
         */
        "htmlFor"?: string;
    }
    /**
     * Switch — shadcn/ui parity. A `role="switch"` toggle, form-associated (submits `value` when on).
     * `change` is emitted from the host with `detail.checked`.
     */
    interface ArtSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "name"?: string;
        /**
          * Emitted after a user toggle; `detail.checked` mirrors `target.checked`.
         */
        "onChange"?: (event: ArtSwitchCustomEvent<{ checked: boolean }>) => void;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'on'
         */
        "value"?: string;
    }
    /**
     * Textarea — shadcn/ui parity. Multi-line text field; grows with content (`field-sizing: content`),
     * form-associated, `input` / `change` emitted from the host with `detail.value` (§3a).
     */
    interface ArtTextarea {
        "autocomplete"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * The `id` of a `<form>` element to associate this element with.
         */
        "form"?: string;
        "hostAriaDescribedby"?: string | null;
        "hostAriaLabel"?: string | null;
        "hostAriaLabelledby"?: string | null;
        /**
          * @default false
         */
        "invalid"?: boolean;
        "maxlength"?: number;
        "minlength"?: number;
        "name"?: string;
        "onChange"?: (event: ArtTextareaCustomEvent<{ value: string }>) => void;
        "onInput"?: (event: ArtTextareaCustomEvent<{ value: string }>) => void;
        "placeholder"?: string;
        /**
          * @default false
         */
        "readonly"?: boolean;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * Initial visible rows; the field still grows with content.
         */
        "rows"?: number;
        /**
          * Density; changes inline padding only (height follows content).
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default ''
         */
        "value"?: string;
    }

    interface ArtButtonAttributes {
        "variant": 'default' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link';
        "size": 'sm' | 'md' | 'lg';
        "icon": boolean;
        "disabled": boolean;
        "loading": boolean;
        "type": 'button' | 'submit' | 'reset';
        "href": string;
        "target": string;
        "rel": string;
        "hostAriaLabel": string | null;
    }
    interface ArtCheckboxAttributes {
        "checked": boolean;
        "indeterminate": boolean;
        "size": 'sm' | 'md' | 'lg';
        "value": string;
        "name": string;
        "disabled": boolean;
        "required": boolean;
        "invalid": boolean;
        "hostAriaLabel": string | null;
        "hostAriaLabelledby": string | null;
        "hostAriaDescribedby": string | null;
    }
    interface ArtHelloAttributes {
        "name": string;
        "variant": 'default' | 'outline';
        "disabled": boolean;
    }
    interface ArtIconAttributes {
        "size": 'sm' | 'md' | 'lg';
        "label": string;
    }
    interface ArtInputAttributes {
        "value": string;
        "type": 'text' | 'email' | 'password' | 'number' | 'search' | 'tel' | 'url' | 'date' | 'time' | 'file';
        "size": 'sm' | 'md' | 'lg';
        "placeholder": string;
        "name": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "invalid": boolean;
        "autocomplete": string;
        "inputmode": string;
        "pattern": string;
        "min": string;
        "max": string;
        "step": string;
        "minlength": number;
        "maxlength": number;
        "hostAriaLabel": string | null;
        "hostAriaLabelledby": string | null;
        "hostAriaDescribedby": string | null;
    }
    interface ArtLabelAttributes {
        "htmlFor": string;
        "disabled": boolean;
    }
    interface ArtSwitchAttributes {
        "checked": boolean;
        "size": 'sm' | 'md' | 'lg';
        "value": string;
        "name": string;
        "disabled": boolean;
        "required": boolean;
        "invalid": boolean;
        "hostAriaLabel": string | null;
        "hostAriaLabelledby": string | null;
        "hostAriaDescribedby": string | null;
    }
    interface ArtTextareaAttributes {
        "value": string;
        "size": 'sm' | 'md' | 'lg';
        "placeholder": string;
        "name": string;
        "disabled": boolean;
        "readonly": boolean;
        "required": boolean;
        "invalid": boolean;
        "rows": number;
        "minlength": number;
        "maxlength": number;
        "autocomplete": string;
        "hostAriaLabel": string | null;
        "hostAriaLabelledby": string | null;
        "hostAriaDescribedby": string | null;
    }

    interface IntrinsicElements {
        "art-button": Omit<ArtButton, keyof ArtButtonAttributes> & { [K in keyof ArtButton & keyof ArtButtonAttributes]?: ArtButton[K] } & { [K in keyof ArtButton & keyof ArtButtonAttributes as `attr:${K}`]?: ArtButtonAttributes[K] } & { [K in keyof ArtButton & keyof ArtButtonAttributes as `prop:${K}`]?: ArtButton[K] };
        "art-checkbox": Omit<ArtCheckbox, keyof ArtCheckboxAttributes> & { [K in keyof ArtCheckbox & keyof ArtCheckboxAttributes]?: ArtCheckbox[K] } & { [K in keyof ArtCheckbox & keyof ArtCheckboxAttributes as `attr:${K}`]?: ArtCheckboxAttributes[K] } & { [K in keyof ArtCheckbox & keyof ArtCheckboxAttributes as `prop:${K}`]?: ArtCheckbox[K] };
        "art-hello": Omit<ArtHello, keyof ArtHelloAttributes> & { [K in keyof ArtHello & keyof ArtHelloAttributes]?: ArtHello[K] } & { [K in keyof ArtHello & keyof ArtHelloAttributes as `attr:${K}`]?: ArtHelloAttributes[K] } & { [K in keyof ArtHello & keyof ArtHelloAttributes as `prop:${K}`]?: ArtHello[K] };
        "art-icon": Omit<ArtIcon, keyof ArtIconAttributes> & { [K in keyof ArtIcon & keyof ArtIconAttributes]?: ArtIcon[K] } & { [K in keyof ArtIcon & keyof ArtIconAttributes as `attr:${K}`]?: ArtIconAttributes[K] } & { [K in keyof ArtIcon & keyof ArtIconAttributes as `prop:${K}`]?: ArtIcon[K] };
        "art-input": Omit<ArtInput, keyof ArtInputAttributes> & { [K in keyof ArtInput & keyof ArtInputAttributes]?: ArtInput[K] } & { [K in keyof ArtInput & keyof ArtInputAttributes as `attr:${K}`]?: ArtInputAttributes[K] } & { [K in keyof ArtInput & keyof ArtInputAttributes as `prop:${K}`]?: ArtInput[K] };
        "art-label": Omit<ArtLabel, keyof ArtLabelAttributes> & { [K in keyof ArtLabel & keyof ArtLabelAttributes]?: ArtLabel[K] } & { [K in keyof ArtLabel & keyof ArtLabelAttributes as `attr:${K}`]?: ArtLabelAttributes[K] } & { [K in keyof ArtLabel & keyof ArtLabelAttributes as `prop:${K}`]?: ArtLabel[K] };
        "art-switch": Omit<ArtSwitch, keyof ArtSwitchAttributes> & { [K in keyof ArtSwitch & keyof ArtSwitchAttributes]?: ArtSwitch[K] } & { [K in keyof ArtSwitch & keyof ArtSwitchAttributes as `attr:${K}`]?: ArtSwitchAttributes[K] } & { [K in keyof ArtSwitch & keyof ArtSwitchAttributes as `prop:${K}`]?: ArtSwitch[K] };
        "art-textarea": Omit<ArtTextarea, keyof ArtTextareaAttributes> & { [K in keyof ArtTextarea & keyof ArtTextareaAttributes]?: ArtTextarea[K] } & { [K in keyof ArtTextarea & keyof ArtTextareaAttributes as `attr:${K}`]?: ArtTextareaAttributes[K] } & { [K in keyof ArtTextarea & keyof ArtTextareaAttributes as `prop:${K}`]?: ArtTextarea[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Button — shadcn/ui parity (ADR-0012): variants `default | secondary | outline | ghost |
             * destructive | link`, sizes `sm | md | lg`, square `icon` buttons, `loading`, and `href`
             * rendering an anchor. Wraps a native `<button>` so `click` stays native (CLAUDE.md §3a);
             * form-associated so `type="submit"` / `type="reset"` work inside a plain `<form>`.
             */
            "art-button": LocalJSX.IntrinsicElements["art-button"] & JSXBase.HTMLAttributes<HTMLArtButtonElement>;
            /**
             * Checkbox — shadcn/ui parity. A `role="checkbox"` button with checked / indeterminate states,
             * form-associated (submits `value` when checked). `change` is emitted from the host with
             * `detail.checked`; Vue `v-model:checked`, Angular `ngModel` (boolean) work out of the box.
             */
            "art-checkbox": LocalJSX.IntrinsicElements["art-checkbox"] & JSXBase.HTMLAttributes<HTMLArtCheckboxElement>;
            /**
             * Phase 0 proof component. Exercises tokens, Tailwind-in-shadow, the focus-ring
             * recipe, a native `click` passing through and a kebab-case custom event.
             * Removed when Button lands.
             */
            "art-hello": LocalJSX.IntrinsicElements["art-hello"] & JSXBase.HTMLAttributes<HTMLArtHelloElement>;
            /**
             * Renders an icon from `@aranghat/icons` (ADR-0007). Icons are never bundled
             * into components: import the icon module you need and pass it as `icon`.
             */
            "art-icon": LocalJSX.IntrinsicElements["art-icon"] & JSXBase.HTMLAttributes<HTMLArtIconElement>;
            /**
             * Input — shadcn/ui parity. Wraps a native `<input>`; form-associated (FormData, validation,
             * reset); `input` / `change` are emitted from the host in response to the native events with
             * `event.target` being `<art-input>` and `detail.value` mirroring `target.value` (§3a). Sizes
             * share the control-height tokens so inputs align with buttons.
             */
            "art-input": LocalJSX.IntrinsicElements["art-input"] & JSXBase.HTMLAttributes<HTMLArtInputElement>;
            /**
             * Label — shadcn/ui parity. A styled `<label>` for any control. Because shadow roots scope
             * ids, `for` is resolved at click time: activating the label focuses the target control
             * (or toggles it for checkbox-like controls), matching native label behaviour across tiers.
             */
            "art-label": LocalJSX.IntrinsicElements["art-label"] & JSXBase.HTMLAttributes<HTMLArtLabelElement>;
            /**
             * Switch — shadcn/ui parity. A `role="switch"` toggle, form-associated (submits `value` when on).
             * `change` is emitted from the host with `detail.checked`.
             */
            "art-switch": LocalJSX.IntrinsicElements["art-switch"] & JSXBase.HTMLAttributes<HTMLArtSwitchElement>;
            /**
             * Textarea — shadcn/ui parity. Multi-line text field; grows with content (`field-sizing: content`),
             * form-associated, `input` / `change` emitted from the host with `detail.value` (§3a).
             */
            "art-textarea": LocalJSX.IntrinsicElements["art-textarea"] & JSXBase.HTMLAttributes<HTMLArtTextareaElement>;
        }
    }
}
