/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Placement } from "@aranghat/primitives/floating";
export { Placement } from "@aranghat/primitives/floating";
export namespace Components {
    /**
     * Hover Card — shadcn/ui parity. A preview card for sighted users to peek at what sits behind
     * a link: opens after a longer hover intent than a tooltip (it is content, not a label), stays
     * open while the pointer is on the card, also opens on keyboard focus. Rendered on the platform
     * top layer (Popover API) and positioned with the floating primitive.
     */
    interface ArtHoverCard {
        /**
          * Grace period after the pointer leaves trigger and card, ms. Defaults to `--art-duration-hover-card-close`.
         */
        "closeDelay"?: number;
        /**
          * Gap between trigger and card, in px.
          * @default 4
         */
        "offset": number;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * Hover intent before opening, ms. Defaults to `--art-duration-hover-card-open`.
         */
        "openDelay"?: number;
        /**
          * Preferred side; flips when there is no room.
          * @default 'bottom'
         */
        "placement": Placement;
    }
    /**
     * Popover — shadcn/ui parity. Rich content anchored to a trigger, opened by click, closed by
     * Escape, an outside click or focus leaving. Rendered on the platform top layer (Popover API)
     * and positioned with the floating primitive. Focus moves into the panel on open and returns
     * to the trigger on close.
     */
    interface ArtPopover {
        /**
          * Accessible name of the panel (`role="dialog"`). Defaults to the trigger's text.
         */
        "label"?: string;
        /**
          * Gap between trigger and panel, in px.
          * @default 4
         */
        "offset": number;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * Preferred side; flips when there is no room.
          * @default 'bottom'
         */
        "placement": Placement;
    }
    /**
     * Tooltip — shadcn/ui parity. A short label that appears when the pointer rests on the
     * trigger (hover intent), on keyboard focus, or on press-and-hold with touch. Rendered on the
     * platform top layer (Popover API) and positioned with the floating primitive; the trigger is
     * described by the tooltip text (`aria-description`), so the label is read even when closed.
     */
    interface ArtTooltip {
        /**
          * Grace period after the pointer leaves, ms. Defaults to `--art-duration-hover-close`.
         */
        "closeDelay"?: number;
        /**
          * Gap between trigger and bubble, in px.
          * @default 4
         */
        "offset": number;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * Hover intent before opening, ms. Defaults to `--art-duration-hover-open`.
         */
        "openDelay"?: number;
        /**
          * Preferred side; flips when there is no room.
          * @default 'top'
         */
        "placement": Placement;
    }
}
export interface ArtHoverCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtHoverCardElement;
}
export interface ArtPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtPopoverElement;
}
export interface ArtTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtTooltipElement;
}
declare global {
    interface HTMLArtHoverCardElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Hover Card — shadcn/ui parity. A preview card for sighted users to peek at what sits behind
     * a link: opens after a longer hover intent than a tooltip (it is content, not a label), stays
     * open while the pointer is on the card, also opens on keyboard focus. Rendered on the platform
     * top layer (Popover API) and positioned with the floating primitive.
     */
    interface HTMLArtHoverCardElement extends Components.ArtHoverCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtHoverCardElementEventMap>(type: K, listener: (this: HTMLArtHoverCardElement, ev: ArtHoverCardCustomEvent<HTMLArtHoverCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtHoverCardElementEventMap>(type: K, listener: (this: HTMLArtHoverCardElement, ev: ArtHoverCardCustomEvent<HTMLArtHoverCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtHoverCardElement: {
        prototype: HTMLArtHoverCardElement;
        new (): HTMLArtHoverCardElement;
    };
    interface HTMLArtPopoverElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Popover — shadcn/ui parity. Rich content anchored to a trigger, opened by click, closed by
     * Escape, an outside click or focus leaving. Rendered on the platform top layer (Popover API)
     * and positioned with the floating primitive. Focus moves into the panel on open and returns
     * to the trigger on close.
     */
    interface HTMLArtPopoverElement extends Components.ArtPopover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtPopoverElementEventMap>(type: K, listener: (this: HTMLArtPopoverElement, ev: ArtPopoverCustomEvent<HTMLArtPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtPopoverElementEventMap>(type: K, listener: (this: HTMLArtPopoverElement, ev: ArtPopoverCustomEvent<HTMLArtPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtPopoverElement: {
        prototype: HTMLArtPopoverElement;
        new (): HTMLArtPopoverElement;
    };
    interface HTMLArtTooltipElementEventMap {
        "open-change": { open: boolean };
    }
    /**
     * Tooltip — shadcn/ui parity. A short label that appears when the pointer rests on the
     * trigger (hover intent), on keyboard focus, or on press-and-hold with touch. Rendered on the
     * platform top layer (Popover API) and positioned with the floating primitive; the trigger is
     * described by the tooltip text (`aria-description`), so the label is read even when closed.
     */
    interface HTMLArtTooltipElement extends Components.ArtTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtTooltipElementEventMap>(type: K, listener: (this: HTMLArtTooltipElement, ev: ArtTooltipCustomEvent<HTMLArtTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtTooltipElementEventMap>(type: K, listener: (this: HTMLArtTooltipElement, ev: ArtTooltipCustomEvent<HTMLArtTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtTooltipElement: {
        prototype: HTMLArtTooltipElement;
        new (): HTMLArtTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "art-hover-card": HTMLArtHoverCardElement;
        "art-popover": HTMLArtPopoverElement;
        "art-tooltip": HTMLArtTooltipElement;
    }
}
declare namespace LocalJSX {
    /**
     * Hover Card — shadcn/ui parity. A preview card for sighted users to peek at what sits behind
     * a link: opens after a longer hover intent than a tooltip (it is content, not a label), stays
     * open while the pointer is on the card, also opens on keyboard focus. Rendered on the platform
     * top layer (Popover API) and positioned with the floating primitive.
     */
    interface ArtHoverCard {
        /**
          * Grace period after the pointer leaves trigger and card, ms. Defaults to `--art-duration-hover-card-close`.
         */
        "closeDelay"?: number;
        /**
          * Gap between trigger and card, in px.
          * @default 4
         */
        "offset"?: number;
        /**
          * Emitted when the user opens or closes the card; `detail.open`.
         */
        "onOpen-change"?: (event: ArtHoverCardCustomEvent<{ open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * Hover intent before opening, ms. Defaults to `--art-duration-hover-card-open`.
         */
        "openDelay"?: number;
        /**
          * Preferred side; flips when there is no room.
          * @default 'bottom'
         */
        "placement"?: Placement;
    }
    /**
     * Popover — shadcn/ui parity. Rich content anchored to a trigger, opened by click, closed by
     * Escape, an outside click or focus leaving. Rendered on the platform top layer (Popover API)
     * and positioned with the floating primitive. Focus moves into the panel on open and returns
     * to the trigger on close.
     */
    interface ArtPopover {
        /**
          * Accessible name of the panel (`role="dialog"`). Defaults to the trigger's text.
         */
        "label"?: string;
        /**
          * Gap between trigger and panel, in px.
          * @default 4
         */
        "offset"?: number;
        /**
          * Emitted when the user opens or closes the popover; `detail.open`.
         */
        "onOpen-change"?: (event: ArtPopoverCustomEvent<{ open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * Preferred side; flips when there is no room.
          * @default 'bottom'
         */
        "placement"?: Placement;
    }
    /**
     * Tooltip — shadcn/ui parity. A short label that appears when the pointer rests on the
     * trigger (hover intent), on keyboard focus, or on press-and-hold with touch. Rendered on the
     * platform top layer (Popover API) and positioned with the floating primitive; the trigger is
     * described by the tooltip text (`aria-description`), so the label is read even when closed.
     */
    interface ArtTooltip {
        /**
          * Grace period after the pointer leaves, ms. Defaults to `--art-duration-hover-close`.
         */
        "closeDelay"?: number;
        /**
          * Gap between trigger and bubble, in px.
          * @default 4
         */
        "offset"?: number;
        /**
          * Emitted when the user opens or closes the tooltip; `detail.open`.
         */
        "onOpen-change"?: (event: ArtTooltipCustomEvent<{ open: boolean }>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * Hover intent before opening, ms. Defaults to `--art-duration-hover-open`.
         */
        "openDelay"?: number;
        /**
          * Preferred side; flips when there is no room.
          * @default 'top'
         */
        "placement"?: Placement;
    }

    interface ArtHoverCardAttributes {
        "placement": Placement;
        "offset": number;
        "open": boolean;
        "openDelay": number;
        "closeDelay": number;
    }
    interface ArtPopoverAttributes {
        "placement": Placement;
        "offset": number;
        "open": boolean;
        "label": string;
    }
    interface ArtTooltipAttributes {
        "placement": Placement;
        "offset": number;
        "open": boolean;
        "openDelay": number;
        "closeDelay": number;
    }

    interface IntrinsicElements {
        "art-hover-card": Omit<ArtHoverCard, keyof ArtHoverCardAttributes> & { [K in keyof ArtHoverCard & keyof ArtHoverCardAttributes]?: ArtHoverCard[K] } & { [K in keyof ArtHoverCard & keyof ArtHoverCardAttributes as `attr:${K}`]?: ArtHoverCardAttributes[K] } & { [K in keyof ArtHoverCard & keyof ArtHoverCardAttributes as `prop:${K}`]?: ArtHoverCard[K] };
        "art-popover": Omit<ArtPopover, keyof ArtPopoverAttributes> & { [K in keyof ArtPopover & keyof ArtPopoverAttributes]?: ArtPopover[K] } & { [K in keyof ArtPopover & keyof ArtPopoverAttributes as `attr:${K}`]?: ArtPopoverAttributes[K] } & { [K in keyof ArtPopover & keyof ArtPopoverAttributes as `prop:${K}`]?: ArtPopover[K] };
        "art-tooltip": Omit<ArtTooltip, keyof ArtTooltipAttributes> & { [K in keyof ArtTooltip & keyof ArtTooltipAttributes]?: ArtTooltip[K] } & { [K in keyof ArtTooltip & keyof ArtTooltipAttributes as `attr:${K}`]?: ArtTooltipAttributes[K] } & { [K in keyof ArtTooltip & keyof ArtTooltipAttributes as `prop:${K}`]?: ArtTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Hover Card — shadcn/ui parity. A preview card for sighted users to peek at what sits behind
             * a link: opens after a longer hover intent than a tooltip (it is content, not a label), stays
             * open while the pointer is on the card, also opens on keyboard focus. Rendered on the platform
             * top layer (Popover API) and positioned with the floating primitive.
             */
            "art-hover-card": LocalJSX.IntrinsicElements["art-hover-card"] & JSXBase.HTMLAttributes<HTMLArtHoverCardElement>;
            /**
             * Popover — shadcn/ui parity. Rich content anchored to a trigger, opened by click, closed by
             * Escape, an outside click or focus leaving. Rendered on the platform top layer (Popover API)
             * and positioned with the floating primitive. Focus moves into the panel on open and returns
             * to the trigger on close.
             */
            "art-popover": LocalJSX.IntrinsicElements["art-popover"] & JSXBase.HTMLAttributes<HTMLArtPopoverElement>;
            /**
             * Tooltip — shadcn/ui parity. A short label that appears when the pointer rests on the
             * trigger (hover intent), on keyboard focus, or on press-and-hold with touch. Rendered on the
             * platform top layer (Popover API) and positioned with the floating primitive; the trigger is
             * described by the tooltip text (`aria-description`), so the label is read even when closed.
             */
            "art-tooltip": LocalJSX.IntrinsicElements["art-tooltip"] & JSXBase.HTMLAttributes<HTMLArtTooltipElement>;
        }
    }
}
