import type { ComponentStories } from '@artui/stories';

const icon = (d: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
const user = icon('<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>');
const card = icon('<rect width="20" height="14" x="2" y="5" rx="2"/><line x1="2" x2="22" y1="10" y2="10"/>');
const settings = icon('<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1-1.51V3a2 2 0 1 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 1 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>');
const logout = icon('<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" x2="9" y1="12" y2="12"/>');
const trigger = `<art-button slot="trigger" variant="outline">Open</art-button>`;
// Ten plain rows, so a five-row cap is visibly a cap rather than the list's own length.
const many = `  <art-menu-item value="profile">Profile</art-menu-item>\n  <art-menu-item value="billing">Billing</art-menu-item>\n  <art-menu-item value="settings">Settings</art-menu-item>\n  <art-menu-item value="shortcuts">Keyboard shortcuts</art-menu-item>\n  <art-menu-item value="team">Team</art-menu-item>\n  <art-menu-item value="invite">Invite users</art-menu-item>\n  <art-menu-item value="new-team">New team</art-menu-item>\n  <art-menu-item value="github">GitHub</art-menu-item>\n  <art-menu-item value="support">Support</art-menu-item>\n  <art-menu-item value="logout">Log out</art-menu-item>`;
const account = `  <art-menu-label>My Account</art-menu-label>\n  <art-menu-separator></art-menu-separator>\n  <art-menu-group>\n    <art-menu-item value="profile">${user}Profile<span slot="shortcut">⇧⌘P</span></art-menu-item>\n    <art-menu-item value="billing">${card}Billing<span slot="shortcut">⌘B</span></art-menu-item>\n    <art-menu-item value="settings">${settings}Settings<span slot="shortcut">⌘S</span></art-menu-item>\n  </art-menu-group>\n  <art-menu-separator></art-menu-separator>\n  <art-menu-item value="logout">${logout}Log out<span slot="shortcut">⇧⌘Q</span></art-menu-item>`;

export const stories: ComponentStories = {
  tag: 'art-dropdown-menu',
  tier: 'navigation',
  variants: ['default'],
  sizes: [],
  states: ['default', 'focus-visible'],
  directional: true,
  screenshot: 'viewport',
  frame: 'inline',
  examples: {
    basic: { title: 'Basic', render: () => `<art-dropdown-menu>\n  ${trigger}\n${account}\n</art-dropdown-menu>`, note: 'A trigger in the `trigger` slot; items, labels, groups and separators in the default slot. Click or ↓ opens; arrows move, typing jumps, Enter activates, Escape closes. `select` on an item (bubbling) carries its `value`.' },
    open: { title: 'Open', render: () => `<art-dropdown-menu open>\n  ${trigger}\n${account}\n</art-dropdown-menu>`, note: 'Controlled with `open`; the panel sits below the trigger on the top layer.' },
    checkboxes: { title: 'Checkbox items', render: () => `<art-dropdown-menu open>\n  <art-button slot="trigger" variant="outline">View</art-button>\n  <art-menu-label>Appearance</art-menu-label>\n  <art-menu-separator></art-menu-separator>\n  <art-menu-item type="checkbox" value="status" checked>Status bar</art-menu-item>\n  <art-menu-item type="checkbox" value="activity" disabled>Activity bar</art-menu-item>\n  <art-menu-item type="checkbox" value="panel">Panel</art-menu-item>\n</art-dropdown-menu>`, note: '`type="checkbox"` items toggle `checked` and emit `change`; call `preventDefault()` on `select` to keep the menu open while toggling several.' },
    radios: { title: 'Radio items', render: () => `<art-dropdown-menu open>\n  <art-button slot="trigger" variant="outline">Panel position</art-button>\n  <art-menu-label>Panel position</art-menu-label>\n  <art-menu-separator></art-menu-separator>\n  <art-menu-radio-group value="bottom">\n    <art-menu-item type="radio" value="top">Top</art-menu-item>\n    <art-menu-item type="radio" value="bottom">Bottom</art-menu-item>\n    <art-menu-item type="radio" value="right">Right</art-menu-item>\n  </art-menu-radio-group>\n</art-dropdown-menu>`, note: '`art-menu-radio-group` keeps one `type="radio"` item checked and emits `value-change`.' },
    submenu: { title: 'Submenu', render: () => `<art-dropdown-menu open>\n  ${trigger}\n  <art-menu-item value="new">New file</art-menu-item>\n  <art-menu-sub open>\n    <art-menu-item slot="trigger">Share</art-menu-item>\n    <art-menu-item value="email">Email</art-menu-item>\n    <art-menu-item value="message">Message</art-menu-item>\n    <art-menu-separator></art-menu-separator>\n    <art-menu-item value="more">More…</art-menu-item>\n  </art-menu-sub>\n  <art-menu-separator></art-menu-separator>\n  <art-menu-item value="delete" variant="destructive">Delete</art-menu-item>\n</art-dropdown-menu>`, note: 'An `art-menu-sub` holds a trigger item and nested items; it opens on hover, → , Enter or Space and closes on ← or Escape. `variant="destructive"` marks a dangerous action.' },
    links: { title: 'Links', render: () => `<art-dropdown-menu>\n  <art-button slot="trigger" variant="outline">Go to</art-button>\n  <art-menu-item href="#dashboard">Dashboard</art-menu-item>\n  <art-menu-item href="#reports">Reports</art-menu-item>\n  <art-menu-item href="https://example.com" target="_blank">Docs ↗</art-menu-item>\n</art-dropdown-menu>`, note: 'An item with `href` is a real link (middle-click and new tabs work).' },
    'visible-items': { title: 'Limited height', render: () => `<art-dropdown-menu open visible-items="5">\n  ${trigger}\n${many}\n</art-dropdown-menu>`, note: '`visible-items` caps the menu at a number of rows rather than a pixel height: the row height is measured from a real item, so it follows the control size. Leave it unset and the menu is as tall as its items, scrolling only when the viewport has no room — set `--art-menu-max-height` instead if you would rather give a length.' },
  },
  render: () => `<art-dropdown-menu>\n  ${trigger}\n${account}\n</art-dropdown-menu>`,
  focusTarget: 'art-dropdown-menu art-button',
  docs: {
    description: 'Displays a menu to the user — such as a set of actions or functions — triggered by a button. shadcn/ui parity on the platform top layer.',
    usage: 'Put a button in the `trigger` slot and items in the default slot. Listen to `select` (bubbling from items; `detail.value`), `change` on checkbox items, `value-change` on a radio group, `open-change` on the menu. React `onSelect` / `onOpenChange`, Vue `v-model:open`, Angular `(select)`.',
    requires: ['base'],
    keyboard: [['Enter / Space / ↓', 'Open (↓ / Enter focus the first item, ↑ the last)'], ['↓ / ↑', 'Move between items (wraps)'], ['Home / End', 'First / last item'], ['Typing', 'Jump to a matching item'], ['→ / Enter / Space on a submenu trigger', 'Open the submenu'], ['← / Escape in a submenu', 'Close it and return to its trigger'], ['Enter / Space', 'Activate the item'], ['Escape', 'Close and return focus to the trigger'], ['Tab', 'Close']],
    roles: 'The trigger gets `aria-haspopup="menu"` and `aria-expanded` (no `aria-controls`: an idref cannot cross the shadow boundary); the panel is `role="menu"` named after the trigger; each `art-menu-item` host is the `menuitem`, `menuitemcheckbox` (`aria-checked`) or `menuitemradio`; separators are `role="separator"`; a submenu trigger carries `aria-haspopup` and `aria-expanded` and its nested menu sits in a `group`. Focus is the highlight and follows the pointer.',
    apg: 'https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/',
    states: '`focus-visible` on the trigger; items highlight on hover / focus, `disabled` items are dimmed and skipped, `checked` items show their indicator, open / closed with enter and exit motion. `active`, `loading` and `invalid` do not apply.',
    tokens: [['`--art-color-bg-popover`, `--art-color-border-default`, `--art-radius-md`, `--art-shadow-popover`, `--art-space-1`', 'panel'], ['`--art-color-bg-accent`, `--art-radius-sm`, `--art-space-2`, `--art-space-1-5`, `--art-space-8`, `--art-font-size-sm`', 'items'], ['`--art-color-fg-muted`, `--art-font-size-xs`, `--art-font-tracking-wide`, `--art-size-icon-md`, `--art-space-3-5`', 'icons, shortcuts, indicators'], ['`--art-color-destructive-fg`, `--art-color-destructive-muted`', 'destructive items'], ['`--art-font-weight-medium`', 'labels'], ['`--art-duration-hover-open`, `--art-duration-hover-close`', 'submenu hover delays']],
    dos: [['Give every item a `value`', 'Parse the item text'], ['Use `variant="destructive"` for irreversible actions', 'Colour random items red'], ['Keep menus shallow (one submenu level)', 'Nest three levels of submenus']],
  },
};
