import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ArtButton, ArtLabel } from '@aranghat/base-angular';
import { ArtCombobox, ArtComboboxItem, SelectValueAccessor } from '@aranghat/components-angular';

@Component({
  selector: 'sample-combobox-form',
  // SelectValueAccessor bridges art-combobox to ngModel / reactive forms (generated by the Angular output target)
  imports: [FormsModule, ArtButton, ArtLabel, ArtCombobox, ArtComboboxItem, SelectValueAccessor],
  template: `
    <form (submit)="onSubmit($event)">
      <art-label for="framework">Framework</art-label>
      <art-combobox id="framework" name="framework" placeholder="Select a framework" required [(ngModel)]="framework">
        <art-combobox-item value="next">Next.js</art-combobox-item>
        <art-combobox-item value="sveltekit">SvelteKit</art-combobox-item>
        <art-combobox-item value="nuxt">Nuxt.js</art-combobox-item>
        <art-combobox-item value="remix" disabled>Remix</art-combobox-item>
        <art-combobox-item value="astro">Astro</art-combobox-item>
      </art-combobox>
      <art-button type="submit">Submit</art-button>
    </form>
  `,
})
export class ComboboxForm {
  framework = '';
  onSubmit(e: Event) {
    e.preventDefault();
    console.log('submitted', Object.fromEntries(new FormData(e.target as HTMLFormElement)), this.framework);
  }
}
