import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ArtButton, ArtLabel } from '@aranghat/base-angular';
import { ArtSelect, ArtSelectItem, SelectValueAccessor } from '@aranghat/components-angular';

@Component({
  selector: 'sample-select-form',
  // SelectValueAccessor bridges art-select to ngModel / reactive forms (generated by the Angular output target)
  imports: [FormsModule, ArtButton, ArtLabel, ArtSelect, ArtSelectItem, SelectValueAccessor],
  template: `
    <form (submit)="onSubmit($event)">
      <art-label for="fruit">Fruit</art-label>
      <art-select id="fruit" name="fruit" placeholder="Select a fruit" required [(ngModel)]="fruit">
        <art-select-item value="apple">Apple</art-select-item>
        <art-select-item value="banana">Banana</art-select-item>
        <art-select-item value="blueberry">Blueberry</art-select-item>
        <art-select-item value="grapes" disabled>Grapes</art-select-item>
        <art-select-item value="pineapple">Pineapple</art-select-item>
      </art-select>
      <art-button type="submit">Submit</art-button>
    </form>
  `,
})
export class SelectForm {
  fruit = '';
  onSubmit(e: Event) {
    e.preventDefault();
    console.log('submitted', Object.fromEntries(new FormData(e.target as HTMLFormElement)), this.fruit);
  }
}
