/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface ArtAppShell {
        /**
          * @default 'offcanvas'
         */
        "collapsible": 'offcanvas' | 'icon' | 'none';
        /**
          * Sidebar expanded (desktop); mirrors the provider.
          * @default true
         */
        "open": boolean;
        /**
          * Sidebar edge (`left` is the inline start).
          * @default 'left'
         */
        "side": 'left' | 'right';
        /**
          * Accessible name of the sidebar landmark.
          * @default 'Sidebar'
         */
        "sidebarLabel": string;
        /**
          * @default 'sidebar'
         */
        "variant": 'sidebar' | 'floating' | 'inset';
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface ArtForgotPassword {
        /**
          * @default "Enter your email and we'll send you a link to reset it"
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "heading": string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * Shows the "back to login" link under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Back to login'
         */
        "loginLabel": string;
        /**
          * Replace the form with the confirmation.
          * @default false
         */
        "sent": boolean;
        /**
          * @default 'We sent you a link to reset your password. It expires in an hour.'
         */
        "sentDescription": string;
        /**
          * @default 'Check your inbox'
         */
        "sentHeading": string;
        /**
          * @default 'Send reset link'
         */
        "submitLabel": string;
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface ArtLogin {
        /**
          * @default 'Enter your email below to login to your account'
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Email only (a magic link / passwordless flow).
          * @default false
         */
        "emailOnly": boolean;
        /**
          * Error line above the button (wrong credentials, network).
         */
        "error"?: string;
        /**
          * Shows the "forgot password" link beside the password label.
         */
        "forgotHref"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "forgotLabel": string;
        /**
          * @default 'Login to your account'
         */
        "heading": string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'Password'
         */
        "passwordLabel": string;
        /**
          * Shows the sign-up line under the button.
         */
        "signupHref"?: string;
        /**
          * @default 'Sign up'
         */
        "signupLabel": string;
        /**
          * @default "Don't have an account?"
         */
        "signupText": string;
        /**
          * @default 'Login'
         */
        "submitLabel": string;
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface ArtSignup {
        /**
          * @default 'Confirm password'
         */
        "confirmLabel": string;
        /**
          * @default 'Enter your details below to create your account'
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Create your account'
         */
        "heading": string;
        /**
          * Drop the confirmation field.
          * @default false
         */
        "hideConfirm": boolean;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * Shows the sign-in line under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Sign in'
         */
        "loginLabel": string;
        /**
          * @default 'Already have an account?'
         */
        "loginText": string;
        /**
          * @default 'Passwords do not match.'
         */
        "mismatchText": string;
        /**
          * @default 'Full name'
         */
        "nameLabel": string;
        /**
          * @default 'Password'
         */
        "passwordLabel": string;
        /**
          * @default 'Create account'
         */
        "submitLabel": string;
    }
}
export interface ArtForgotPasswordCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtForgotPasswordElement;
}
export interface ArtLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtLoginElement;
}
export interface ArtSignupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtSignupElement;
}
declare global {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface HTMLArtAppShellElement extends Components.ArtAppShell, HTMLStencilElement {
    }
    var HTMLArtAppShellElement: {
        prototype: HTMLArtAppShellElement;
        new (): HTMLArtAppShellElement;
    };
    interface HTMLArtForgotPasswordElementEventMap {
        "submit": { email: string };
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface HTMLArtForgotPasswordElement extends Components.ArtForgotPassword, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtForgotPasswordElementEventMap>(type: K, listener: (this: HTMLArtForgotPasswordElement, ev: ArtForgotPasswordCustomEvent<HTMLArtForgotPasswordElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtForgotPasswordElementEventMap>(type: K, listener: (this: HTMLArtForgotPasswordElement, ev: ArtForgotPasswordCustomEvent<HTMLArtForgotPasswordElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtForgotPasswordElement: {
        prototype: HTMLArtForgotPasswordElement;
        new (): HTMLArtForgotPasswordElement;
    };
    interface HTMLArtLoginElementEventMap {
        "submit": { email: string; password: string };
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface HTMLArtLoginElement extends Components.ArtLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtLoginElementEventMap>(type: K, listener: (this: HTMLArtLoginElement, ev: ArtLoginCustomEvent<HTMLArtLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtLoginElementEventMap>(type: K, listener: (this: HTMLArtLoginElement, ev: ArtLoginCustomEvent<HTMLArtLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtLoginElement: {
        prototype: HTMLArtLoginElement;
        new (): HTMLArtLoginElement;
    };
    interface HTMLArtSignupElementEventMap {
        "submit": { name: string; email: string; password: string };
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface HTMLArtSignupElement extends Components.ArtSignup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtSignupElementEventMap>(type: K, listener: (this: HTMLArtSignupElement, ev: ArtSignupCustomEvent<HTMLArtSignupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtSignupElementEventMap>(type: K, listener: (this: HTMLArtSignupElement, ev: ArtSignupCustomEvent<HTMLArtSignupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtSignupElement: {
        prototype: HTMLArtSignupElement;
        new (): HTMLArtSignupElement;
    };
    interface HTMLElementTagNameMap {
        "art-app-shell": HTMLArtAppShellElement;
        "art-forgot-password": HTMLArtForgotPasswordElement;
        "art-login": HTMLArtLoginElement;
        "art-signup": HTMLArtSignupElement;
    }
}
declare namespace LocalJSX {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface ArtAppShell {
        /**
          * @default 'offcanvas'
         */
        "collapsible"?: 'offcanvas' | 'icon' | 'none';
        /**
          * Sidebar expanded (desktop); mirrors the provider.
          * @default true
         */
        "open"?: boolean;
        /**
          * Sidebar edge (`left` is the inline start).
          * @default 'left'
         */
        "side"?: 'left' | 'right';
        /**
          * Accessible name of the sidebar landmark.
          * @default 'Sidebar'
         */
        "sidebarLabel"?: string;
        /**
          * @default 'sidebar'
         */
        "variant"?: 'sidebar' | 'floating' | 'inset';
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface ArtForgotPassword {
        /**
          * @default "Enter your email and we'll send you a link to reset it"
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "heading"?: string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Shows the "back to login" link under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Back to login'
         */
        "loginLabel"?: string;
        /**
          * Emitted when the form is submitted with a valid email; `detail.email`.
         */
        "onSubmit"?: (event: ArtForgotPasswordCustomEvent<{ email: string }>) => void;
        /**
          * Replace the form with the confirmation.
          * @default false
         */
        "sent"?: boolean;
        /**
          * @default 'We sent you a link to reset your password. It expires in an hour.'
         */
        "sentDescription"?: string;
        /**
          * @default 'Check your inbox'
         */
        "sentHeading"?: string;
        /**
          * @default 'Send reset link'
         */
        "submitLabel"?: string;
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface ArtLogin {
        /**
          * @default 'Enter your email below to login to your account'
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Email only (a magic link / passwordless flow).
          * @default false
         */
        "emailOnly"?: boolean;
        /**
          * Error line above the button (wrong credentials, network).
         */
        "error"?: string;
        /**
          * Shows the "forgot password" link beside the password label.
         */
        "forgotHref"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "forgotLabel"?: string;
        /**
          * @default 'Login to your account'
         */
        "heading"?: string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the form is submitted with valid fields; `detail.email`, `detail.password` (empty when `email-only`).
         */
        "onSubmit"?: (event: ArtLoginCustomEvent<{ email: string; password: string }>) => void;
        /**
          * @default 'Password'
         */
        "passwordLabel"?: string;
        /**
          * Shows the sign-up line under the button.
         */
        "signupHref"?: string;
        /**
          * @default 'Sign up'
         */
        "signupLabel"?: string;
        /**
          * @default "Don't have an account?"
         */
        "signupText"?: string;
        /**
          * @default 'Login'
         */
        "submitLabel"?: string;
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface ArtSignup {
        /**
          * @default 'Confirm password'
         */
        "confirmLabel"?: string;
        /**
          * @default 'Enter your details below to create your account'
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Create your account'
         */
        "heading"?: string;
        /**
          * Drop the confirmation field.
          * @default false
         */
        "hideConfirm"?: boolean;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Shows the sign-in line under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Sign in'
         */
        "loginLabel"?: string;
        /**
          * @default 'Already have an account?'
         */
        "loginText"?: string;
        /**
          * @default 'Passwords do not match.'
         */
        "mismatchText"?: string;
        /**
          * @default 'Full name'
         */
        "nameLabel"?: string;
        /**
          * Emitted when the form is submitted with valid, matching fields; `detail.name`, `detail.email`, `detail.password`.
         */
        "onSubmit"?: (event: ArtSignupCustomEvent<{ name: string; email: string; password: string }>) => void;
        /**
          * @default 'Password'
         */
        "passwordLabel"?: string;
        /**
          * @default 'Create account'
         */
        "submitLabel"?: string;
    }

    interface ArtAppShellAttributes {
        "open": boolean;
        "side": 'left' | 'right';
        "variant": 'sidebar' | 'floating' | 'inset';
        "collapsible": 'offcanvas' | 'icon' | 'none';
        "sidebarLabel": string;
    }
    interface ArtForgotPasswordAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "emailLabel": string;
        "loginHref": string;
        "loginLabel": string;
        "sent": boolean;
        "sentHeading": string;
        "sentDescription": string;
        "loading": boolean;
        "error": string;
    }
    interface ArtLoginAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "emailLabel": string;
        "passwordLabel": string;
        "forgotHref": string;
        "forgotLabel": string;
        "signupHref": string;
        "signupLabel": string;
        "signupText": string;
        "emailOnly": boolean;
        "loading": boolean;
        "error": string;
    }
    interface ArtSignupAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "nameLabel": string;
        "emailLabel": string;
        "passwordLabel": string;
        "confirmLabel": string;
        "mismatchText": string;
        "hideConfirm": boolean;
        "loginHref": string;
        "loginLabel": string;
        "loginText": string;
        "loading": boolean;
        "error": string;
    }

    interface IntrinsicElements {
        "art-app-shell": Omit<ArtAppShell, keyof ArtAppShellAttributes> & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes]?: ArtAppShell[K] } & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes as `attr:${K}`]?: ArtAppShellAttributes[K] } & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes as `prop:${K}`]?: ArtAppShell[K] };
        "art-forgot-password": Omit<ArtForgotPassword, keyof ArtForgotPasswordAttributes> & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes]?: ArtForgotPassword[K] } & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes as `attr:${K}`]?: ArtForgotPasswordAttributes[K] } & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes as `prop:${K}`]?: ArtForgotPassword[K] };
        "art-login": Omit<ArtLogin, keyof ArtLoginAttributes> & { [K in keyof ArtLogin & keyof ArtLoginAttributes]?: ArtLogin[K] } & { [K in keyof ArtLogin & keyof ArtLoginAttributes as `attr:${K}`]?: ArtLoginAttributes[K] } & { [K in keyof ArtLogin & keyof ArtLoginAttributes as `prop:${K}`]?: ArtLogin[K] };
        "art-signup": Omit<ArtSignup, keyof ArtSignupAttributes> & { [K in keyof ArtSignup & keyof ArtSignupAttributes]?: ArtSignup[K] } & { [K in keyof ArtSignup & keyof ArtSignupAttributes as `attr:${K}`]?: ArtSignupAttributes[K] } & { [K in keyof ArtSignup & keyof ArtSignupAttributes as `prop:${K}`]?: ArtSignup[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
             * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
             * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
             * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
             * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
             */
            "art-app-shell": LocalJSX.IntrinsicElements["art-app-shell"] & JSXBase.HTMLAttributes<HTMLArtAppShellElement>;
            /**
             * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
             * reset link is on its way. You own what happens on `submit` (`detail.email`).
             */
            "art-forgot-password": LocalJSX.IntrinsicElements["art-forgot-password"] & JSXBase.HTMLAttributes<HTMLArtForgotPasswordElement>;
            /**
             * Login — the shadcn login block as one element: a card with email and password, a "forgot
             * password" link, the submit button, optional social buttons and a sign-up link. The widget
             * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
             */
            "art-login": LocalJSX.IntrinsicElements["art-login"] & JSXBase.HTMLAttributes<HTMLArtLoginElement>;
            /**
             * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
             * card, the create-account button, optional social buttons and a sign-in link. The widget checks
             * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
             * `detail.password`).
             */
            "art-signup": LocalJSX.IntrinsicElements["art-signup"] & JSXBase.HTMLAttributes<HTMLArtSignupElement>;
        }
    }
}
