/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface ArtAppShell {
        /**
          * @default 'offcanvas'
         */
        "collapsible": 'offcanvas' | 'icon' | 'none';
        /**
          * Sidebar expanded (desktop); mirrors the provider.
          * @default true
         */
        "open": boolean;
        /**
          * Sidebar edge (`left` is the inline start).
          * @default 'left'
         */
        "side": 'left' | 'right';
        /**
          * Accessible name of the sidebar landmark.
          * @default 'Sidebar'
         */
        "sidebarLabel": string;
        /**
          * @default 'sidebar'
         */
        "variant": 'sidebar' | 'floating' | 'inset';
    }
    /**
     * Data Table Page — the chrome around a data table (shadcn "tasks" example): page heading and
     * actions, a toolbar with the filter field, faceted filters, a reset and the view menu, the
     * table itself, and a footer with the selection count, rows-per-page, the page position and
     * first / previous / next / last. The page owns no data: drive it from `createTableState`
     * (`@aranghat/components`) — feed `selected`, `total`, `page`, `page-count`, `page-size` from the
     * snapshot and listen to `filter-change`, `page-change`, `page-size-change`.
     */
    interface ArtDataTablePage {
        /**
          * @default "Here's a list of your tasks for this month."
         */
        "description": string;
        /**
          * Current filter text (mirror it from your state to keep the field in sync).
          * @default ''
         */
        "filter": string;
        /**
          * @default 'Filter…'
         */
        "filterPlaceholder": string;
        /**
          * @default 'Welcome back!'
         */
        "heading": string;
        /**
          * Drop the filter field (keep `filters` / `view` slots).
          * @default false
         */
        "hideFilter": boolean;
        /**
          * @default 1
         */
        "page": number;
        /**
          * @default 1
         */
        "pageCount": number;
        /**
          * @default 10
         */
        "pageSize": number;
        /**
          * Choices for rows per page, comma-separated.
          * @default '10,20,30,40,50'
         */
        "pageSizes": string;
        /**
          * Selected rows (over every page).
          * @default 0
         */
        "selected": number;
        /**
          * Rows after filtering.
          * @default 0
         */
        "total": number;
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface ArtForgotPassword {
        /**
          * @default "Enter your email and we'll send you a link to reset it"
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "heading": string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * Shows the "back to login" link under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Back to login'
         */
        "loginLabel": string;
        /**
          * Replace the form with the confirmation.
          * @default false
         */
        "sent": boolean;
        /**
          * @default 'We sent you a link to reset your password. It expires in an hour.'
         */
        "sentDescription": string;
        /**
          * @default 'Check your inbox'
         */
        "sentHeading": string;
        /**
          * @default 'Send reset link'
         */
        "submitLabel": string;
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface ArtLogin {
        /**
          * @default 'Enter your email below to login to your account'
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Email only (a magic link / passwordless flow).
          * @default false
         */
        "emailOnly": boolean;
        /**
          * Error line above the button (wrong credentials, network).
         */
        "error"?: string;
        /**
          * Shows the "forgot password" link beside the password label.
         */
        "forgotHref"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "forgotLabel": string;
        /**
          * @default 'Login to your account'
         */
        "heading": string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'Password'
         */
        "passwordLabel": string;
        /**
          * Shows the sign-up line under the button.
         */
        "signupHref"?: string;
        /**
          * @default 'Sign up'
         */
        "signupLabel": string;
        /**
          * @default "Don't have an account?"
         */
        "signupText": string;
        /**
          * @default 'Login'
         */
        "submitLabel": string;
    }
    /**
     * Notification Centre — a bell with an unread count that opens a panel of
     * `art-notification-item`s: a heading, "Mark all as read", an all / unread filter, the list and
     * an empty state. `inline` renders the panel in place (a settings page, the docs). Clicking an
     * item emits `select` and marks it read; the count follows the items' `unread` attributes.
     */
    interface ArtNotificationCentre {
        /**
          * @default 'All'
         */
        "allLabel": string;
        /**
          * @default 'New notifications will appear here.'
         */
        "emptyDescription": string;
        /**
          * @default "You're all caught up"
         */
        "emptyHeading": string;
        /**
          * Show every item or only the unread ones.
          * @default 'all'
         */
        "filter": 'all' | 'unread';
        /**
          * @default 'Notifications'
         */
        "heading": string;
        /**
          * Render the panel in place, without the bell.
          * @default false
         */
        "inline": boolean;
        /**
          * @default 'Mark all as read'
         */
        "markAllLabel": string;
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default 'Notifications'
         */
        "triggerLabel": string;
        /**
          * @default 'Unread'
         */
        "unreadLabel": string;
    }
    /**
     * Notification Item — one row of an `art-notification-centre`: media, heading, description,
     * time, and the unread dot. The whole row activates (`select`, then the centre marks it read);
     * with `href` it is a link. Extra actions go in the default slot and stay clickable on their own.
     */
    interface ArtNotificationItem {
        "description"?: string;
        /**
          * @default ''
         */
        "heading": string;
        /**
          * Makes the heading a link.
         */
        "href"?: string;
        /**
          * Relative or absolute time, as text (`2m ago`).
         */
        "time"?: string;
        /**
          * @default false
         */
        "unread": boolean;
        /**
          * Reported by `select`.
          * @default ''
         */
        "value": string;
    }
    /**
     * Onboarding Wizard — a multi-step flow: a stepper (numbers, check marks, the current step),
     * one `art-wizard-step` shown at a time, and Back / Next / Finish (and Skip on optional steps).
     * `step` is 1-based; `step-change` is cancelable so you can validate before moving on.
     */
    interface ArtOnboardingWizard {
        /**
          * @default 'Back'
         */
        "backLabel": string;
        /**
          * @default 'Finish'
         */
        "finishLabel": string;
        /**
          * Accessible name of the stepper.
          * @default 'Setup'
         */
        "label": string;
        /**
          * Spinner on the Next / Finish button; moves are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'Next'
         */
        "nextLabel": string;
        /**
          * Stepper beside the content instead of above it.
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
        /**
          * @default 'Skip'
         */
        "skipLabel": string;
        /**
          * Current step, 1-based.
          * @default 1
         */
        "step": number;
    }
    /**
     * Settings Page — the shadcn settings layout: a page heading, a section nav (vertical beside the
     * content on wide screens, a scrolling row above it on narrow ones) and the section's heading,
     * description and content. Links are plain `<a slot="nav">`s (or router links) and
     * `aria-current="page"` marks the open section.
     */
    interface ArtSettingsPage {
        /**
          * @default 'Manage your account settings and set e-mail preferences.'
         */
        "description": string;
        /**
          * @default 'Settings'
         */
        "heading": string;
        /**
          * Accessible name of the section nav.
          * @default 'Settings sections'
         */
        "navLabel": string;
        "sectionDescription"?: string;
        /**
          * The open section's heading.
         */
        "sectionHeading"?: string;
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface ArtSignup {
        /**
          * @default 'Confirm password'
         */
        "confirmLabel": string;
        /**
          * @default 'Enter your details below to create your account'
         */
        "description": string;
        /**
          * @default 'Email'
         */
        "emailLabel": string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Create your account'
         */
        "heading": string;
        /**
          * Drop the confirmation field.
          * @default false
         */
        "hideConfirm": boolean;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading": boolean;
        /**
          * Shows the sign-in line under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Sign in'
         */
        "loginLabel": string;
        /**
          * @default 'Already have an account?'
         */
        "loginText": string;
        /**
          * @default 'Passwords do not match.'
         */
        "mismatchText": string;
        /**
          * @default 'Full name'
         */
        "nameLabel": string;
        /**
          * @default 'Password'
         */
        "passwordLabel": string;
        /**
          * @default 'Create account'
         */
        "submitLabel": string;
    }
    /**
     * State Page — a full-page empty / 404 / 500 state: a centred `art-empty` with an optional
     * status code, default copy per `kind` (override with `heading` / `description`), media and
     * actions. Fill the viewport (or a docs frame) and put the way out in `actions`.
     */
    interface ArtStatePage {
        /**
          * Status code shown above the heading (`404`, `500`).
         */
        "code"?: string;
        "description"?: string;
        "heading"?: string;
        /**
          * Which state; picks the default copy.
          * @default 'empty'
         */
        "kind": 'empty' | 'not-found' | 'error';
    }
    /**
     * Wizard Step — one step of an `art-onboarding-wizard`: its `label` / `description` feed the
     * stepper, its content is shown while it is the current step (the wizard hides the others).
     */
    interface ArtWizardStep {
        "description"?: string;
        /**
          * @default ''
         */
        "label": string;
        /**
          * May be skipped (the wizard offers a Skip button on it).
          * @default false
         */
        "optional": boolean;
    }
}
export interface ArtDataTablePageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtDataTablePageElement;
}
export interface ArtForgotPasswordCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtForgotPasswordElement;
}
export interface ArtLoginCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtLoginElement;
}
export interface ArtNotificationCentreCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtNotificationCentreElement;
}
export interface ArtNotificationItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtNotificationItemElement;
}
export interface ArtOnboardingWizardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtOnboardingWizardElement;
}
export interface ArtSignupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtSignupElement;
}
declare global {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface HTMLArtAppShellElement extends Components.ArtAppShell, HTMLStencilElement {
    }
    var HTMLArtAppShellElement: {
        prototype: HTMLArtAppShellElement;
        new (): HTMLArtAppShellElement;
    };
    interface HTMLArtDataTablePageElementEventMap {
        "filter-change": { value: string };
        "page-change": { page: number };
        "page-size-change": { pageSize: number };
    }
    /**
     * Data Table Page — the chrome around a data table (shadcn "tasks" example): page heading and
     * actions, a toolbar with the filter field, faceted filters, a reset and the view menu, the
     * table itself, and a footer with the selection count, rows-per-page, the page position and
     * first / previous / next / last. The page owns no data: drive it from `createTableState`
     * (`@aranghat/components`) — feed `selected`, `total`, `page`, `page-count`, `page-size` from the
     * snapshot and listen to `filter-change`, `page-change`, `page-size-change`.
     */
    interface HTMLArtDataTablePageElement extends Components.ArtDataTablePage, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtDataTablePageElementEventMap>(type: K, listener: (this: HTMLArtDataTablePageElement, ev: ArtDataTablePageCustomEvent<HTMLArtDataTablePageElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtDataTablePageElementEventMap>(type: K, listener: (this: HTMLArtDataTablePageElement, ev: ArtDataTablePageCustomEvent<HTMLArtDataTablePageElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtDataTablePageElement: {
        prototype: HTMLArtDataTablePageElement;
        new (): HTMLArtDataTablePageElement;
    };
    interface HTMLArtForgotPasswordElementEventMap {
        "submit": { email: string };
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface HTMLArtForgotPasswordElement extends Components.ArtForgotPassword, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtForgotPasswordElementEventMap>(type: K, listener: (this: HTMLArtForgotPasswordElement, ev: ArtForgotPasswordCustomEvent<HTMLArtForgotPasswordElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtForgotPasswordElementEventMap>(type: K, listener: (this: HTMLArtForgotPasswordElement, ev: ArtForgotPasswordCustomEvent<HTMLArtForgotPasswordElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtForgotPasswordElement: {
        prototype: HTMLArtForgotPasswordElement;
        new (): HTMLArtForgotPasswordElement;
    };
    interface HTMLArtLoginElementEventMap {
        "submit": { email: string; password: string };
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface HTMLArtLoginElement extends Components.ArtLogin, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtLoginElementEventMap>(type: K, listener: (this: HTMLArtLoginElement, ev: ArtLoginCustomEvent<HTMLArtLoginElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtLoginElementEventMap>(type: K, listener: (this: HTMLArtLoginElement, ev: ArtLoginCustomEvent<HTMLArtLoginElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtLoginElement: {
        prototype: HTMLArtLoginElement;
        new (): HTMLArtLoginElement;
    };
    interface HTMLArtNotificationCentreElementEventMap {
        "open-change": { open: boolean };
        "read-all": void;
    }
    /**
     * Notification Centre — a bell with an unread count that opens a panel of
     * `art-notification-item`s: a heading, "Mark all as read", an all / unread filter, the list and
     * an empty state. `inline` renders the panel in place (a settings page, the docs). Clicking an
     * item emits `select` and marks it read; the count follows the items' `unread` attributes.
     */
    interface HTMLArtNotificationCentreElement extends Components.ArtNotificationCentre, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtNotificationCentreElementEventMap>(type: K, listener: (this: HTMLArtNotificationCentreElement, ev: ArtNotificationCentreCustomEvent<HTMLArtNotificationCentreElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtNotificationCentreElementEventMap>(type: K, listener: (this: HTMLArtNotificationCentreElement, ev: ArtNotificationCentreCustomEvent<HTMLArtNotificationCentreElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtNotificationCentreElement: {
        prototype: HTMLArtNotificationCentreElement;
        new (): HTMLArtNotificationCentreElement;
    };
    interface HTMLArtNotificationItemElementEventMap {
        "select": { value: string };
    }
    /**
     * Notification Item — one row of an `art-notification-centre`: media, heading, description,
     * time, and the unread dot. The whole row activates (`select`, then the centre marks it read);
     * with `href` it is a link. Extra actions go in the default slot and stay clickable on their own.
     */
    interface HTMLArtNotificationItemElement extends Components.ArtNotificationItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtNotificationItemElementEventMap>(type: K, listener: (this: HTMLArtNotificationItemElement, ev: ArtNotificationItemCustomEvent<HTMLArtNotificationItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtNotificationItemElementEventMap>(type: K, listener: (this: HTMLArtNotificationItemElement, ev: ArtNotificationItemCustomEvent<HTMLArtNotificationItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtNotificationItemElement: {
        prototype: HTMLArtNotificationItemElement;
        new (): HTMLArtNotificationItemElement;
    };
    interface HTMLArtOnboardingWizardElementEventMap {
        "step-change": { step: number; from: number };
        "finish": void;
    }
    /**
     * Onboarding Wizard — a multi-step flow: a stepper (numbers, check marks, the current step),
     * one `art-wizard-step` shown at a time, and Back / Next / Finish (and Skip on optional steps).
     * `step` is 1-based; `step-change` is cancelable so you can validate before moving on.
     */
    interface HTMLArtOnboardingWizardElement extends Components.ArtOnboardingWizard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtOnboardingWizardElementEventMap>(type: K, listener: (this: HTMLArtOnboardingWizardElement, ev: ArtOnboardingWizardCustomEvent<HTMLArtOnboardingWizardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtOnboardingWizardElementEventMap>(type: K, listener: (this: HTMLArtOnboardingWizardElement, ev: ArtOnboardingWizardCustomEvent<HTMLArtOnboardingWizardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtOnboardingWizardElement: {
        prototype: HTMLArtOnboardingWizardElement;
        new (): HTMLArtOnboardingWizardElement;
    };
    /**
     * Settings Page — the shadcn settings layout: a page heading, a section nav (vertical beside the
     * content on wide screens, a scrolling row above it on narrow ones) and the section's heading,
     * description and content. Links are plain `<a slot="nav">`s (or router links) and
     * `aria-current="page"` marks the open section.
     */
    interface HTMLArtSettingsPageElement extends Components.ArtSettingsPage, HTMLStencilElement {
    }
    var HTMLArtSettingsPageElement: {
        prototype: HTMLArtSettingsPageElement;
        new (): HTMLArtSettingsPageElement;
    };
    interface HTMLArtSignupElementEventMap {
        "submit": { name: string; email: string; password: string };
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface HTMLArtSignupElement extends Components.ArtSignup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtSignupElementEventMap>(type: K, listener: (this: HTMLArtSignupElement, ev: ArtSignupCustomEvent<HTMLArtSignupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtSignupElementEventMap>(type: K, listener: (this: HTMLArtSignupElement, ev: ArtSignupCustomEvent<HTMLArtSignupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtSignupElement: {
        prototype: HTMLArtSignupElement;
        new (): HTMLArtSignupElement;
    };
    /**
     * State Page — a full-page empty / 404 / 500 state: a centred `art-empty` with an optional
     * status code, default copy per `kind` (override with `heading` / `description`), media and
     * actions. Fill the viewport (or a docs frame) and put the way out in `actions`.
     */
    interface HTMLArtStatePageElement extends Components.ArtStatePage, HTMLStencilElement {
    }
    var HTMLArtStatePageElement: {
        prototype: HTMLArtStatePageElement;
        new (): HTMLArtStatePageElement;
    };
    /**
     * Wizard Step — one step of an `art-onboarding-wizard`: its `label` / `description` feed the
     * stepper, its content is shown while it is the current step (the wizard hides the others).
     */
    interface HTMLArtWizardStepElement extends Components.ArtWizardStep, HTMLStencilElement {
    }
    var HTMLArtWizardStepElement: {
        prototype: HTMLArtWizardStepElement;
        new (): HTMLArtWizardStepElement;
    };
    interface HTMLElementTagNameMap {
        "art-app-shell": HTMLArtAppShellElement;
        "art-data-table-page": HTMLArtDataTablePageElement;
        "art-forgot-password": HTMLArtForgotPasswordElement;
        "art-login": HTMLArtLoginElement;
        "art-notification-centre": HTMLArtNotificationCentreElement;
        "art-notification-item": HTMLArtNotificationItemElement;
        "art-onboarding-wizard": HTMLArtOnboardingWizardElement;
        "art-settings-page": HTMLArtSettingsPageElement;
        "art-signup": HTMLArtSignupElement;
        "art-state-page": HTMLArtStatePageElement;
        "art-wizard-step": HTMLArtWizardStepElement;
    }
}
declare namespace LocalJSX {
    /**
     * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
     * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
     * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
     * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
     * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
     */
    interface ArtAppShell {
        /**
          * @default 'offcanvas'
         */
        "collapsible"?: 'offcanvas' | 'icon' | 'none';
        /**
          * Sidebar expanded (desktop); mirrors the provider.
          * @default true
         */
        "open"?: boolean;
        /**
          * Sidebar edge (`left` is the inline start).
          * @default 'left'
         */
        "side"?: 'left' | 'right';
        /**
          * Accessible name of the sidebar landmark.
          * @default 'Sidebar'
         */
        "sidebarLabel"?: string;
        /**
          * @default 'sidebar'
         */
        "variant"?: 'sidebar' | 'floating' | 'inset';
    }
    /**
     * Data Table Page — the chrome around a data table (shadcn "tasks" example): page heading and
     * actions, a toolbar with the filter field, faceted filters, a reset and the view menu, the
     * table itself, and a footer with the selection count, rows-per-page, the page position and
     * first / previous / next / last. The page owns no data: drive it from `createTableState`
     * (`@aranghat/components`) — feed `selected`, `total`, `page`, `page-count`, `page-size` from the
     * snapshot and listen to `filter-change`, `page-change`, `page-size-change`.
     */
    interface ArtDataTablePage {
        /**
          * @default "Here's a list of your tasks for this month."
         */
        "description"?: string;
        /**
          * Current filter text (mirror it from your state to keep the field in sync).
          * @default ''
         */
        "filter"?: string;
        /**
          * @default 'Filter…'
         */
        "filterPlaceholder"?: string;
        /**
          * @default 'Welcome back!'
         */
        "heading"?: string;
        /**
          * Drop the filter field (keep `filters` / `view` slots).
          * @default false
         */
        "hideFilter"?: boolean;
        /**
          * The filter field changed; `detail.value`.
         */
        "onFilter-change"?: (event: ArtDataTablePageCustomEvent<{ value: string }>) => void;
        /**
          * A pagination control was used; `detail.page`.
         */
        "onPage-change"?: (event: ArtDataTablePageCustomEvent<{ page: number }>) => void;
        /**
          * Rows per page changed; `detail.pageSize`.
         */
        "onPage-size-change"?: (event: ArtDataTablePageCustomEvent<{ pageSize: number }>) => void;
        /**
          * @default 1
         */
        "page"?: number;
        /**
          * @default 1
         */
        "pageCount"?: number;
        /**
          * @default 10
         */
        "pageSize"?: number;
        /**
          * Choices for rows per page, comma-separated.
          * @default '10,20,30,40,50'
         */
        "pageSizes"?: string;
        /**
          * Selected rows (over every page).
          * @default 0
         */
        "selected"?: number;
        /**
          * Rows after filtering.
          * @default 0
         */
        "total"?: number;
    }
    /**
     * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
     * reset link is on its way. You own what happens on `submit` (`detail.email`).
     */
    interface ArtForgotPassword {
        /**
          * @default "Enter your email and we'll send you a link to reset it"
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "heading"?: string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Shows the "back to login" link under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Back to login'
         */
        "loginLabel"?: string;
        /**
          * Emitted when the form is submitted with a valid email; `detail.email`.
         */
        "onSubmit"?: (event: ArtForgotPasswordCustomEvent<{ email: string }>) => void;
        /**
          * Replace the form with the confirmation.
          * @default false
         */
        "sent"?: boolean;
        /**
          * @default 'We sent you a link to reset your password. It expires in an hour.'
         */
        "sentDescription"?: string;
        /**
          * @default 'Check your inbox'
         */
        "sentHeading"?: string;
        /**
          * @default 'Send reset link'
         */
        "submitLabel"?: string;
    }
    /**
     * Login — the shadcn login block as one element: a card with email and password, a "forgot
     * password" link, the submit button, optional social buttons and a sign-up link. The widget
     * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
     */
    interface ArtLogin {
        /**
          * @default 'Enter your email below to login to your account'
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Email only (a magic link / passwordless flow).
          * @default false
         */
        "emailOnly"?: boolean;
        /**
          * Error line above the button (wrong credentials, network).
         */
        "error"?: string;
        /**
          * Shows the "forgot password" link beside the password label.
         */
        "forgotHref"?: string;
        /**
          * @default 'Forgot your password?'
         */
        "forgotLabel"?: string;
        /**
          * @default 'Login to your account'
         */
        "heading"?: string;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the form is submitted with valid fields; `detail.email`, `detail.password` (empty when `email-only`).
         */
        "onSubmit"?: (event: ArtLoginCustomEvent<{ email: string; password: string }>) => void;
        /**
          * @default 'Password'
         */
        "passwordLabel"?: string;
        /**
          * Shows the sign-up line under the button.
         */
        "signupHref"?: string;
        /**
          * @default 'Sign up'
         */
        "signupLabel"?: string;
        /**
          * @default "Don't have an account?"
         */
        "signupText"?: string;
        /**
          * @default 'Login'
         */
        "submitLabel"?: string;
    }
    /**
     * Notification Centre — a bell with an unread count that opens a panel of
     * `art-notification-item`s: a heading, "Mark all as read", an all / unread filter, the list and
     * an empty state. `inline` renders the panel in place (a settings page, the docs). Clicking an
     * item emits `select` and marks it read; the count follows the items' `unread` attributes.
     */
    interface ArtNotificationCentre {
        /**
          * @default 'All'
         */
        "allLabel"?: string;
        /**
          * @default 'New notifications will appear here.'
         */
        "emptyDescription"?: string;
        /**
          * @default "You're all caught up"
         */
        "emptyHeading"?: string;
        /**
          * Show every item or only the unread ones.
          * @default 'all'
         */
        "filter"?: 'all' | 'unread';
        /**
          * @default 'Notifications'
         */
        "heading"?: string;
        /**
          * Render the panel in place, without the bell.
          * @default false
         */
        "inline"?: boolean;
        /**
          * @default 'Mark all as read'
         */
        "markAllLabel"?: string;
        /**
          * Emitted when the user opens or closes the panel; `detail.open`.
         */
        "onOpen-change"?: (event: ArtNotificationCentreCustomEvent<{ open: boolean }>) => void;
        /**
          * Emitted when "Mark all as read" is pressed (the items are marked read too).
         */
        "onRead-all"?: (event: ArtNotificationCentreCustomEvent<void>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default 'Notifications'
         */
        "triggerLabel"?: string;
        /**
          * @default 'Unread'
         */
        "unreadLabel"?: string;
    }
    /**
     * Notification Item — one row of an `art-notification-centre`: media, heading, description,
     * time, and the unread dot. The whole row activates (`select`, then the centre marks it read);
     * with `href` it is a link. Extra actions go in the default slot and stay clickable on their own.
     */
    interface ArtNotificationItem {
        "description"?: string;
        /**
          * @default ''
         */
        "heading"?: string;
        /**
          * Makes the heading a link.
         */
        "href"?: string;
        /**
          * Emitted when the row is activated; `detail.value`. Cancelable — `preventDefault()` keeps it unread.
         */
        "onSelect"?: (event: ArtNotificationItemCustomEvent<{ value: string }>) => void;
        /**
          * Relative or absolute time, as text (`2m ago`).
         */
        "time"?: string;
        /**
          * @default false
         */
        "unread"?: boolean;
        /**
          * Reported by `select`.
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Onboarding Wizard — a multi-step flow: a stepper (numbers, check marks, the current step),
     * one `art-wizard-step` shown at a time, and Back / Next / Finish (and Skip on optional steps).
     * `step` is 1-based; `step-change` is cancelable so you can validate before moving on.
     */
    interface ArtOnboardingWizard {
        /**
          * @default 'Back'
         */
        "backLabel"?: string;
        /**
          * @default 'Finish'
         */
        "finishLabel"?: string;
        /**
          * Accessible name of the stepper.
          * @default 'Setup'
         */
        "label"?: string;
        /**
          * Spinner on the Next / Finish button; moves are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'Next'
         */
        "nextLabel"?: string;
        /**
          * Emitted when Finish is pressed on the last step.
         */
        "onFinish"?: (event: ArtOnboardingWizardCustomEvent<void>) => void;
        /**
          * Emitted before the step changes; `detail.step` (target), `detail.from`. Cancelable — `preventDefault()` stays on the current step.
         */
        "onStep-change"?: (event: ArtOnboardingWizardCustomEvent<{ step: number; from: number }>) => void;
        /**
          * Stepper beside the content instead of above it.
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
        /**
          * @default 'Skip'
         */
        "skipLabel"?: string;
        /**
          * Current step, 1-based.
          * @default 1
         */
        "step"?: number;
    }
    /**
     * Settings Page — the shadcn settings layout: a page heading, a section nav (vertical beside the
     * content on wide screens, a scrolling row above it on narrow ones) and the section's heading,
     * description and content. Links are plain `<a slot="nav">`s (or router links) and
     * `aria-current="page"` marks the open section.
     */
    interface ArtSettingsPage {
        /**
          * @default 'Manage your account settings and set e-mail preferences.'
         */
        "description"?: string;
        /**
          * @default 'Settings'
         */
        "heading"?: string;
        /**
          * Accessible name of the section nav.
          * @default 'Settings sections'
         */
        "navLabel"?: string;
        "sectionDescription"?: string;
        /**
          * The open section's heading.
         */
        "sectionHeading"?: string;
    }
    /**
     * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
     * card, the create-account button, optional social buttons and a sign-in link. The widget checks
     * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
     * `detail.password`).
     */
    interface ArtSignup {
        /**
          * @default 'Confirm password'
         */
        "confirmLabel"?: string;
        /**
          * @default 'Enter your details below to create your account'
         */
        "description"?: string;
        /**
          * @default 'Email'
         */
        "emailLabel"?: string;
        /**
          * Error line above the button.
         */
        "error"?: string;
        /**
          * @default 'Create your account'
         */
        "heading"?: string;
        /**
          * Drop the confirmation field.
          * @default false
         */
        "hideConfirm"?: boolean;
        /**
          * Spinner on the button; submits are ignored meanwhile.
          * @default false
         */
        "loading"?: boolean;
        /**
          * Shows the sign-in line under the button.
         */
        "loginHref"?: string;
        /**
          * @default 'Sign in'
         */
        "loginLabel"?: string;
        /**
          * @default 'Already have an account?'
         */
        "loginText"?: string;
        /**
          * @default 'Passwords do not match.'
         */
        "mismatchText"?: string;
        /**
          * @default 'Full name'
         */
        "nameLabel"?: string;
        /**
          * Emitted when the form is submitted with valid, matching fields; `detail.name`, `detail.email`, `detail.password`.
         */
        "onSubmit"?: (event: ArtSignupCustomEvent<{ name: string; email: string; password: string }>) => void;
        /**
          * @default 'Password'
         */
        "passwordLabel"?: string;
        /**
          * @default 'Create account'
         */
        "submitLabel"?: string;
    }
    /**
     * State Page — a full-page empty / 404 / 500 state: a centred `art-empty` with an optional
     * status code, default copy per `kind` (override with `heading` / `description`), media and
     * actions. Fill the viewport (or a docs frame) and put the way out in `actions`.
     */
    interface ArtStatePage {
        /**
          * Status code shown above the heading (`404`, `500`).
         */
        "code"?: string;
        "description"?: string;
        "heading"?: string;
        /**
          * Which state; picks the default copy.
          * @default 'empty'
         */
        "kind"?: 'empty' | 'not-found' | 'error';
    }
    /**
     * Wizard Step — one step of an `art-onboarding-wizard`: its `label` / `description` feed the
     * stepper, its content is shown while it is the current step (the wizard hides the others).
     */
    interface ArtWizardStep {
        "description"?: string;
        /**
          * @default ''
         */
        "label"?: string;
        /**
          * May be skipped (the wizard offers a Skip button on it).
          * @default false
         */
        "optional"?: boolean;
    }

    interface ArtAppShellAttributes {
        "open": boolean;
        "side": 'left' | 'right';
        "variant": 'sidebar' | 'floating' | 'inset';
        "collapsible": 'offcanvas' | 'icon' | 'none';
        "sidebarLabel": string;
    }
    interface ArtDataTablePageAttributes {
        "heading": string;
        "description": string;
        "filter": string;
        "filterPlaceholder": string;
        "hideFilter": boolean;
        "selected": number;
        "total": number;
        "page": number;
        "pageCount": number;
        "pageSize": number;
        "pageSizes": string;
    }
    interface ArtForgotPasswordAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "emailLabel": string;
        "loginHref": string;
        "loginLabel": string;
        "sent": boolean;
        "sentHeading": string;
        "sentDescription": string;
        "loading": boolean;
        "error": string;
    }
    interface ArtLoginAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "emailLabel": string;
        "passwordLabel": string;
        "forgotHref": string;
        "forgotLabel": string;
        "signupHref": string;
        "signupLabel": string;
        "signupText": string;
        "emailOnly": boolean;
        "loading": boolean;
        "error": string;
    }
    interface ArtNotificationCentreAttributes {
        "open": boolean;
        "inline": boolean;
        "heading": string;
        "triggerLabel": string;
        "markAllLabel": string;
        "allLabel": string;
        "unreadLabel": string;
        "emptyHeading": string;
        "emptyDescription": string;
        "filter": 'all' | 'unread';
    }
    interface ArtNotificationItemAttributes {
        "value": string;
        "heading": string;
        "description": string;
        "time": string;
        "unread": boolean;
        "href": string;
    }
    interface ArtOnboardingWizardAttributes {
        "step": number;
        "orientation": 'horizontal' | 'vertical';
        "label": string;
        "backLabel": string;
        "nextLabel": string;
        "finishLabel": string;
        "skipLabel": string;
        "loading": boolean;
    }
    interface ArtSettingsPageAttributes {
        "heading": string;
        "description": string;
        "navLabel": string;
        "sectionHeading": string;
        "sectionDescription": string;
    }
    interface ArtSignupAttributes {
        "heading": string;
        "description": string;
        "submitLabel": string;
        "nameLabel": string;
        "emailLabel": string;
        "passwordLabel": string;
        "confirmLabel": string;
        "mismatchText": string;
        "hideConfirm": boolean;
        "loginHref": string;
        "loginLabel": string;
        "loginText": string;
        "loading": boolean;
        "error": string;
    }
    interface ArtStatePageAttributes {
        "kind": 'empty' | 'not-found' | 'error';
        "code": string;
        "heading": string;
        "description": string;
    }
    interface ArtWizardStepAttributes {
        "label": string;
        "description": string;
        "optional": boolean;
    }

    interface IntrinsicElements {
        "art-app-shell": Omit<ArtAppShell, keyof ArtAppShellAttributes> & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes]?: ArtAppShell[K] } & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes as `attr:${K}`]?: ArtAppShellAttributes[K] } & { [K in keyof ArtAppShell & keyof ArtAppShellAttributes as `prop:${K}`]?: ArtAppShell[K] };
        "art-data-table-page": Omit<ArtDataTablePage, keyof ArtDataTablePageAttributes> & { [K in keyof ArtDataTablePage & keyof ArtDataTablePageAttributes]?: ArtDataTablePage[K] } & { [K in keyof ArtDataTablePage & keyof ArtDataTablePageAttributes as `attr:${K}`]?: ArtDataTablePageAttributes[K] } & { [K in keyof ArtDataTablePage & keyof ArtDataTablePageAttributes as `prop:${K}`]?: ArtDataTablePage[K] };
        "art-forgot-password": Omit<ArtForgotPassword, keyof ArtForgotPasswordAttributes> & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes]?: ArtForgotPassword[K] } & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes as `attr:${K}`]?: ArtForgotPasswordAttributes[K] } & { [K in keyof ArtForgotPassword & keyof ArtForgotPasswordAttributes as `prop:${K}`]?: ArtForgotPassword[K] };
        "art-login": Omit<ArtLogin, keyof ArtLoginAttributes> & { [K in keyof ArtLogin & keyof ArtLoginAttributes]?: ArtLogin[K] } & { [K in keyof ArtLogin & keyof ArtLoginAttributes as `attr:${K}`]?: ArtLoginAttributes[K] } & { [K in keyof ArtLogin & keyof ArtLoginAttributes as `prop:${K}`]?: ArtLogin[K] };
        "art-notification-centre": Omit<ArtNotificationCentre, keyof ArtNotificationCentreAttributes> & { [K in keyof ArtNotificationCentre & keyof ArtNotificationCentreAttributes]?: ArtNotificationCentre[K] } & { [K in keyof ArtNotificationCentre & keyof ArtNotificationCentreAttributes as `attr:${K}`]?: ArtNotificationCentreAttributes[K] } & { [K in keyof ArtNotificationCentre & keyof ArtNotificationCentreAttributes as `prop:${K}`]?: ArtNotificationCentre[K] };
        "art-notification-item": Omit<ArtNotificationItem, keyof ArtNotificationItemAttributes> & { [K in keyof ArtNotificationItem & keyof ArtNotificationItemAttributes]?: ArtNotificationItem[K] } & { [K in keyof ArtNotificationItem & keyof ArtNotificationItemAttributes as `attr:${K}`]?: ArtNotificationItemAttributes[K] } & { [K in keyof ArtNotificationItem & keyof ArtNotificationItemAttributes as `prop:${K}`]?: ArtNotificationItem[K] };
        "art-onboarding-wizard": Omit<ArtOnboardingWizard, keyof ArtOnboardingWizardAttributes> & { [K in keyof ArtOnboardingWizard & keyof ArtOnboardingWizardAttributes]?: ArtOnboardingWizard[K] } & { [K in keyof ArtOnboardingWizard & keyof ArtOnboardingWizardAttributes as `attr:${K}`]?: ArtOnboardingWizardAttributes[K] } & { [K in keyof ArtOnboardingWizard & keyof ArtOnboardingWizardAttributes as `prop:${K}`]?: ArtOnboardingWizard[K] };
        "art-settings-page": Omit<ArtSettingsPage, keyof ArtSettingsPageAttributes> & { [K in keyof ArtSettingsPage & keyof ArtSettingsPageAttributes]?: ArtSettingsPage[K] } & { [K in keyof ArtSettingsPage & keyof ArtSettingsPageAttributes as `attr:${K}`]?: ArtSettingsPageAttributes[K] } & { [K in keyof ArtSettingsPage & keyof ArtSettingsPageAttributes as `prop:${K}`]?: ArtSettingsPage[K] };
        "art-signup": Omit<ArtSignup, keyof ArtSignupAttributes> & { [K in keyof ArtSignup & keyof ArtSignupAttributes]?: ArtSignup[K] } & { [K in keyof ArtSignup & keyof ArtSignupAttributes as `attr:${K}`]?: ArtSignupAttributes[K] } & { [K in keyof ArtSignup & keyof ArtSignupAttributes as `prop:${K}`]?: ArtSignup[K] };
        "art-state-page": Omit<ArtStatePage, keyof ArtStatePageAttributes> & { [K in keyof ArtStatePage & keyof ArtStatePageAttributes]?: ArtStatePage[K] } & { [K in keyof ArtStatePage & keyof ArtStatePageAttributes as `attr:${K}`]?: ArtStatePageAttributes[K] } & { [K in keyof ArtStatePage & keyof ArtStatePageAttributes as `prop:${K}`]?: ArtStatePage[K] };
        "art-wizard-step": Omit<ArtWizardStep, keyof ArtWizardStepAttributes> & { [K in keyof ArtWizardStep & keyof ArtWizardStepAttributes]?: ArtWizardStep[K] } & { [K in keyof ArtWizardStep & keyof ArtWizardStepAttributes as `attr:${K}`]?: ArtWizardStepAttributes[K] } & { [K in keyof ArtWizardStep & keyof ArtWizardStepAttributes as `prop:${K}`]?: ArtWizardStep[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * App Shell — the dashboard frame in one element: a Sidebar (header / groups / footer slots), a
             * header bar with the sidebar trigger, and the page. Composes `art-sidebar-provider`,
             * `art-sidebar`, `art-sidebar-inset` and `art-sidebar-trigger` from `@aranghat/navigation`;
             * everything the Sidebar offers (`side`, `variant`, `collapsible`, ⌘ / Ctrl + B, the off-canvas
             * sheet below md) works unchanged, and the sidebar family finds its sidebar through the slots.
             */
            "art-app-shell": LocalJSX.IntrinsicElements["art-app-shell"] & JSXBase.HTMLAttributes<HTMLArtAppShellElement>;
            /**
             * Data Table Page — the chrome around a data table (shadcn "tasks" example): page heading and
             * actions, a toolbar with the filter field, faceted filters, a reset and the view menu, the
             * table itself, and a footer with the selection count, rows-per-page, the page position and
             * first / previous / next / last. The page owns no data: drive it from `createTableState`
             * (`@aranghat/components`) — feed `selected`, `total`, `page`, `page-count`, `page-size` from the
             * snapshot and listen to `filter-change`, `page-change`, `page-size-change`.
             */
            "art-data-table-page": LocalJSX.IntrinsicElements["art-data-table-page"] & JSXBase.HTMLAttributes<HTMLArtDataTablePageElement>;
            /**
             * Forgot Password — a card that asks for the account email and, once `sent`, confirms that the
             * reset link is on its way. You own what happens on `submit` (`detail.email`).
             */
            "art-forgot-password": LocalJSX.IntrinsicElements["art-forgot-password"] & JSXBase.HTMLAttributes<HTMLArtForgotPasswordElement>;
            /**
             * Login — the shadcn login block as one element: a card with email and password, a "forgot
             * password" link, the submit button, optional social buttons and a sign-up link. The widget
             * owns the form; you own what happens on `submit` (`detail.email`, `detail.password`).
             */
            "art-login": LocalJSX.IntrinsicElements["art-login"] & JSXBase.HTMLAttributes<HTMLArtLoginElement>;
            /**
             * Notification Centre — a bell with an unread count that opens a panel of
             * `art-notification-item`s: a heading, "Mark all as read", an all / unread filter, the list and
             * an empty state. `inline` renders the panel in place (a settings page, the docs). Clicking an
             * item emits `select` and marks it read; the count follows the items' `unread` attributes.
             */
            "art-notification-centre": LocalJSX.IntrinsicElements["art-notification-centre"] & JSXBase.HTMLAttributes<HTMLArtNotificationCentreElement>;
            /**
             * Notification Item — one row of an `art-notification-centre`: media, heading, description,
             * time, and the unread dot. The whole row activates (`select`, then the centre marks it read);
             * with `href` it is a link. Extra actions go in the default slot and stay clickable on their own.
             */
            "art-notification-item": LocalJSX.IntrinsicElements["art-notification-item"] & JSXBase.HTMLAttributes<HTMLArtNotificationItemElement>;
            /**
             * Onboarding Wizard — a multi-step flow: a stepper (numbers, check marks, the current step),
             * one `art-wizard-step` shown at a time, and Back / Next / Finish (and Skip on optional steps).
             * `step` is 1-based; `step-change` is cancelable so you can validate before moving on.
             */
            "art-onboarding-wizard": LocalJSX.IntrinsicElements["art-onboarding-wizard"] & JSXBase.HTMLAttributes<HTMLArtOnboardingWizardElement>;
            /**
             * Settings Page — the shadcn settings layout: a page heading, a section nav (vertical beside the
             * content on wide screens, a scrolling row above it on narrow ones) and the section's heading,
             * description and content. Links are plain `<a slot="nav">`s (or router links) and
             * `aria-current="page"` marks the open section.
             */
            "art-settings-page": LocalJSX.IntrinsicElements["art-settings-page"] & JSXBase.HTMLAttributes<HTMLArtSettingsPageElement>;
            /**
             * Signup — the shadcn signup block as one element: name, email, password and confirmation in a
             * card, the create-account button, optional social buttons and a sign-in link. The widget checks
             * that the passwords match; you own what happens on `submit` (`detail.name`, `detail.email`,
             * `detail.password`).
             */
            "art-signup": LocalJSX.IntrinsicElements["art-signup"] & JSXBase.HTMLAttributes<HTMLArtSignupElement>;
            /**
             * State Page — a full-page empty / 404 / 500 state: a centred `art-empty` with an optional
             * status code, default copy per `kind` (override with `heading` / `description`), media and
             * actions. Fill the viewport (or a docs frame) and put the way out in `actions`.
             */
            "art-state-page": LocalJSX.IntrinsicElements["art-state-page"] & JSXBase.HTMLAttributes<HTMLArtStatePageElement>;
            /**
             * Wizard Step — one step of an `art-onboarding-wizard`: its `label` / `description` feed the
             * stepper, its content is shown while it is the current step (the wizard hides the others).
             */
            "art-wizard-step": LocalJSX.IntrinsicElements["art-wizard-step"] & JSXBase.HTMLAttributes<HTMLArtWizardStepElement>;
        }
    }
}
