// Generated by @artui/wrapper-entries — do not edit.
export { ArtHelloOverlay as HelloOverlay } from './components/art-hello-overlay.js';
export type { StencilReactComponent } from '@stencil/react-output-target/runtime';
