// Consumers import exactly one stylesheet (CLAUDE.md §4) …
import '@aranghat/tokens/aranghat.css';
// … and register only the elements they use.
import { defineCustomElement as defineButton } from '@aranghat/base/button';
import { defineCustomElement as defineIcon } from '@aranghat/base/icon';
import { defineCustomElement as defineLabel } from '@aranghat/base/label';
import { defineCustomElement as defineInput } from '@aranghat/base/input';
import { defineCustomElement as defineTextarea } from '@aranghat/base/textarea';
import { defineCustomElement as defineCheckbox } from '@aranghat/base/checkbox';
import { defineCustomElement as defineSwitch } from '@aranghat/base/switch';
import { defineCustomElement as defineRadioGroup } from '@aranghat/base/radio-group';
import { defineCustomElement as defineNativeSelect } from '@aranghat/base/native-select';
import { defineCustomElement as defineToggle } from '@aranghat/base/toggle';
import { defineCustomElement as defineToggleGroup } from '@aranghat/base/toggle-group';
import { defineCustomElement as defineSlider } from '@aranghat/base/slider';
import { defineCustomElement as defineSeparator } from '@aranghat/base/separator';
import { defineCustomElement as defineBadge } from '@aranghat/base/badge';
import { defineCustomElement as defineKbd } from '@aranghat/base/kbd';
import { defineCustomElement as defineKbdGroup } from '@aranghat/base/kbd-group';
import { defineCustomElement as defineSkeleton } from '@aranghat/base/skeleton';
import { defineCustomElement as defineSpinner } from '@aranghat/base/spinner';
import { defineCustomElement as defineProgress } from '@aranghat/base/progress';
import { defineCustomElement as defineButtonGroup } from '@aranghat/base/button-group';
import { defineCustomElement as defineButtonGroupText } from '@aranghat/base/button-group-text';
import { defineCustomElement as defineInputGroup } from '@aranghat/base/input-group';
import { defineCustomElement as defineField } from '@aranghat/base/field';
import { defineCustomElement as defineFieldSet } from '@aranghat/base/field-set';
import { defineCustomElement as defineFieldGroup } from '@aranghat/base/field-group';
import { defineCustomElement as defineInputOtp } from '@aranghat/base/input-otp';
import { defineCustomElement as defineAspectRatio } from '@aranghat/base/aspect-ratio';
import { defineCustomElement as defineCard } from '@aranghat/base/card';
import { defineCustomElement as defineItem } from '@aranghat/base/item';
import { defineCustomElement as defineItemGroup } from '@aranghat/base/item-group';
import { defineCustomElement as defineEmpty } from '@aranghat/base/empty';
import { defineCustomElement as defineMarker } from '@aranghat/base/marker';
import { defineCustomElement as defineTable } from '@aranghat/base/table';
import { defineCustomElement as defineTypography } from '@aranghat/base/typography';
import { defineCustomElement as defineTooltip } from '@aranghat/components/tooltip';
import { defineCustomElement as definePopover } from '@aranghat/components/popover';
import { defineCustomElement as defineHoverCard } from '@aranghat/components/hover-card';
import { defineCustomElement as defineCollapsible } from '@aranghat/components/collapsible';
import { defineCustomElement as defineAccordion } from '@aranghat/components/accordion';
import { defineCustomElement as defineAccordionItem } from '@aranghat/components/accordion-item';
import { defineCustomElement as defineTabs } from '@aranghat/components/tabs';
import { defineCustomElement as defineTabPanel } from '@aranghat/components/tab-panel';
import { defineCustomElement as defineAlert } from '@aranghat/components/alert';
import { defineCustomElement as defineAvatar } from '@aranghat/components/avatar';
import { defineCustomElement as defineScrollArea } from '@aranghat/components/scroll-area';
import { defineCustomElement as defineResizable } from '@aranghat/components/resizable';
import { defineCustomElement as defineResizablePanel } from '@aranghat/components/resizable-panel';
import { defineCustomElement as defineResizableHandle } from '@aranghat/components/resizable-handle';
import { defineCustomElement as defineSelect } from '@aranghat/components/select';
import { defineCustomElement as defineSelectItem } from '@aranghat/components/select-item';
import { defineCustomElement as defineSelectGroup } from '@aranghat/components/select-group';
import { defineCustomElement as defineCommand } from '@aranghat/components/command';
import { defineCustomElement as defineCommandItem } from '@aranghat/components/command-item';
import { defineCustomElement as defineCommandGroup } from '@aranghat/components/command-group';
import { defineCustomElement as defineCombobox } from '@aranghat/components/combobox';
import { defineCustomElement as defineComboboxItem } from '@aranghat/components/combobox-item';
import { defineCustomElement as defineComboboxGroup } from '@aranghat/components/combobox-group';
import { defineCustomElement as defineCalendar } from '@aranghat/components/calendar';
import { defineCustomElement as defineDatePicker } from '@aranghat/components/date-picker';
import { defineCustomElement as defineToaster } from '@aranghat/components/toaster';
import { defineCustomElement as defineToast } from '@aranghat/components/toast';
import { defineCustomElement as defineCarousel } from '@aranghat/components/carousel';
import { defineCustomElement as defineCarouselItem } from '@aranghat/components/carousel-item';
import { defineCustomElement as defineBubble } from '@aranghat/components/bubble';
import { defineCustomElement as defineBubbleGroup } from '@aranghat/components/bubble-group';
import { defineCustomElement as defineMessage } from '@aranghat/components/message';
import { defineCustomElement as defineMessageGroup } from '@aranghat/components/message-group';
import { defineCustomElement as defineMessageScroller } from '@aranghat/components/message-scroller';
import { defineCustomElement as defineMessageScrollerItem } from '@aranghat/components/message-scroller-item';
import { defineCustomElement as defineAttachment } from '@aranghat/components/attachment';
import { defineCustomElement as defineAttachmentGroup } from '@aranghat/components/attachment-group';
import { defineCustomElement as defineQuestionnaire } from '@aranghat/components/questionnaire';
import { defineCustomElement as defineBreadcrumb } from '@aranghat/navigation/breadcrumb';
import { defineCustomElement as defineBreadcrumbItem } from '@aranghat/navigation/breadcrumb-item';
import { defineCustomElement as definePagination } from '@aranghat/navigation/pagination';
import { defineCustomElement as defineDropdownMenu } from '@aranghat/navigation/dropdown-menu';
import { defineCustomElement as defineMenuItem } from '@aranghat/navigation/menu-item';
import { defineCustomElement as defineMenuRadioGroup } from '@aranghat/navigation/menu-radio-group';
import { defineCustomElement as defineMenuLabel } from '@aranghat/navigation/menu-label';
import { defineCustomElement as defineMenuSeparator } from '@aranghat/navigation/menu-separator';
import { defineCustomElement as defineMenuGroup } from '@aranghat/navigation/menu-group';
import { defineCustomElement as defineMenuSub } from '@aranghat/navigation/menu-sub';
import { defineCustomElement as defineContextMenu } from '@aranghat/navigation/context-menu';
import { defineCustomElement as defineMenubar } from '@aranghat/navigation/menubar';
import { defineCustomElement as defineMenubarMenu } from '@aranghat/navigation/menubar-menu';
import { defineCustomElement as defineNavigationMenu } from '@aranghat/navigation/navigation-menu';
import { defineCustomElement as defineNavigationMenuItem } from '@aranghat/navigation/navigation-menu-item';
import { defineCustomElement as defineNavigationMenuLink } from '@aranghat/navigation/navigation-menu-link';
import { defineCustomElement as defineSidebarProvider } from '@aranghat/navigation/sidebar-provider';
import { defineCustomElement as defineSidebarMenu } from '@aranghat/navigation/sidebar-menu';
import { defineCustomElement as defineSidebarMenuItem } from '@aranghat/navigation/sidebar-menu-item';
import { defineCustomElement as defineSidebarMenuButton } from '@aranghat/navigation/sidebar-menu-button';
import { defineCustomElement as defineSidebarGroup } from '@aranghat/navigation/sidebar-group';
import { defineCustomElement as defineSidebarInset } from '@aranghat/navigation/sidebar-inset';
import { defineCustomElement as defineSidebarTrigger } from '@aranghat/navigation/sidebar-trigger';
import { defineCustomElement as defineSidebarMenuSub } from '@aranghat/navigation/sidebar-menu-sub';
import { defineCustomElement as defineTopNav } from '@aranghat/navigation/top-nav';
import { defineCustomElement as defineTreeView } from '@aranghat/navigation/tree-view';
import { defineCustomElement as defineTreeItem } from '@aranghat/navigation/tree-item';
import { defineCustomElement as defineSidebar } from '@aranghat/navigation/sidebar';
import { defineCustomElement as defineDialog } from '@aranghat/modals/dialog';
import { defineCustomElement as defineAlertDialog } from '@aranghat/modals/alert-dialog';
import { defineCustomElement as defineSheet } from '@aranghat/modals/sheet';
import { defineCustomElement as defineDrawer } from '@aranghat/modals/drawer';
import { defineCustomElement as defineAppShell } from '@aranghat/widgets/app-shell';
import { defineCustomElement as defineLogin } from '@aranghat/widgets/login';
import { defineCustomElement as defineSignup } from '@aranghat/widgets/signup';
import { defineCustomElement as defineForgotPassword } from '@aranghat/widgets/forgot-password';
import { defineCustomElement as defineStatePage } from '@aranghat/widgets/state-page';
import { defineCustomElement as defineSettingsPage } from '@aranghat/widgets/settings-page';
import { defineCustomElement as defineRadio } from '@aranghat/base/radio';
import { defineCustomElement as defineDataTablePage } from '@aranghat/widgets/data-table-page';
import { defineCustomElement as defineOnboardingWizard } from '@aranghat/widgets/onboarding-wizard';
import { defineCustomElement as defineWizardStep } from '@aranghat/widgets/wizard-step';
import { defineCustomElement as defineNotificationCentre } from '@aranghat/widgets/notification-centre';
import { defineCustomElement as defineNotificationItem } from '@aranghat/widgets/notification-item';
import { defineCustomElement as defineNavRail } from '@aranghat/extended/nav-rail';
import { defineCustomElement as defineNavRailItem } from '@aranghat/extended/nav-rail-item';
import { defineCustomElement as defineNavSection } from '@aranghat/extended/nav-section';
import { defineCustomElement as defineNavLink } from '@aranghat/extended/nav-link';
import { defineCustomElement as defineMegaMenu } from '@aranghat/extended/mega-menu';
import { defineCustomElement as defineMegaMenuItem } from '@aranghat/extended/mega-menu-item';
import { defineCustomElement as defineMegaMenuGroup } from '@aranghat/extended/mega-menu-group';
import { defineCustomElement as defineMegaMenuLink } from '@aranghat/extended/mega-menu-link';
import './sandbox.css';

defineButton();
defineIcon();
defineLabel();
defineInput();
defineTextarea();
defineCheckbox();
defineSwitch();
defineRadioGroup();
defineNativeSelect();
defineToggle();
defineToggleGroup();
defineSlider();
defineSeparator();
defineBadge();
defineKbd();
defineKbdGroup();
defineSkeleton();
defineSpinner();
defineProgress();
defineButtonGroup();
defineButtonGroupText();
defineInputGroup();
defineField();
defineFieldSet();
defineFieldGroup();
defineInputOtp();
defineAspectRatio();
defineCard();
defineItem();
defineItemGroup();
defineEmpty();
defineMarker();
defineTable();
defineTypography();
defineTooltip();
definePopover();
defineHoverCard();
defineCollapsible();
defineAccordion();
defineAccordionItem();
defineTabs();
defineTabPanel();
defineAlert();
defineAvatar();
defineScrollArea();
defineResizable();
defineResizablePanel();
defineResizableHandle();
defineSelect();
defineSelectItem();
defineSelectGroup();
defineCommand();
defineCommandItem();
defineCommandGroup();
defineCombobox();
defineComboboxItem();
defineComboboxGroup();
defineCalendar();
defineDatePicker();
defineToaster();
defineToast();
defineCarousel();
defineCarouselItem();
defineBubble();
defineBubbleGroup();
defineMessage();
defineMessageGroup();
defineMessageScroller();
defineMessageScrollerItem();
defineAttachment();
defineAttachmentGroup();
defineQuestionnaire();
defineBreadcrumb();
defineBreadcrumbItem();
definePagination();
defineDropdownMenu();
defineMenuItem();
defineMenuRadioGroup();
defineMenuLabel();
defineMenuSeparator();
defineMenuGroup();
defineMenuSub();
defineContextMenu();
defineMenubar();
defineMenubarMenu();
defineNavigationMenu();
defineNavigationMenuItem();
defineNavigationMenuLink();
defineSidebarProvider();
defineSidebarMenu();
defineSidebarMenuItem();
defineSidebarMenuButton();
defineSidebarGroup();
defineSidebarInset();
defineSidebarTrigger();
defineSidebarMenuSub();
defineTopNav();
defineTreeView();
defineTreeItem();
defineSidebar();
defineDialog();
defineAlertDialog();
defineSheet();
defineDrawer();
defineAppShell();
defineLogin();
defineSignup();
defineForgotPassword();
defineStatePage();
defineSettingsPage();
defineRadio();
defineDataTablePage();
defineOnboardingWizard();
defineWizardStep();
defineNotificationCentre();
defineNotificationItem();
defineNavRail();
defineNavRailItem();
defineNavSection();
defineNavLink();
defineMegaMenu();
defineMegaMenuItem();
defineMegaMenuGroup();
defineMegaMenuLink();

// Every sample is a real file under src/samples/<component>/<example>.html — the
// docs site embeds these files verbatim, and the smoke test asserts each renders.
const samples = import.meta.glob('./samples/**/*.html', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
const app = document.getElementById('app')!;
for (const [path, html] of Object.entries(samples).sort()) {
  const id = path.replace('./samples/', '').replace(/\.html$/, '');
  const section = document.createElement('section');
  section.dataset.sample = id;
  section.innerHTML = `<h2>${id}</h2>${html}`;
  app.append(section);
}

// theme toggle for manual checks
document.addEventListener('keydown', (e) => {
  if (e.key === 'd' && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    const root = document.documentElement;
    root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
  }
});
