// Consumers import exactly one stylesheet (CLAUDE.md §4) …
import '@aranghat/tokens/aranghat.css';
// … and register only the elements they use.
import { defineCustomElement as defineButton } from '@aranghat/base/button';
import { defineCustomElement as defineHello } from '@aranghat/base/hello';
import { defineCustomElement as defineIcon } from '@aranghat/base/icon';
import { defineCustomElement as defineHelloOverlay } from '@aranghat/modals/hello-overlay';
import { defineCustomElement as defineLabel } from '@aranghat/base/label';
import { defineCustomElement as defineInput } from '@aranghat/base/input';
import { defineCustomElement as defineTextarea } from '@aranghat/base/textarea';
import { defineCustomElement as defineCheckbox } from '@aranghat/base/checkbox';
import { defineCustomElement as defineSwitch } from '@aranghat/base/switch';
import { defineCustomElement as defineRadioGroup } from '@aranghat/base/radio-group';
import { defineCustomElement as defineNativeSelect } from '@aranghat/base/native-select';
import { defineCustomElement as defineToggle } from '@aranghat/base/toggle';
import { defineCustomElement as defineToggleGroup } from '@aranghat/base/toggle-group';
import { defineCustomElement as defineSlider } from '@aranghat/base/slider';
import { defineCustomElement as defineSeparator } from '@aranghat/base/separator';
import { defineCustomElement as defineBadge } from '@aranghat/base/badge';
import { defineCustomElement as defineKbd } from '@aranghat/base/kbd';
import { defineCustomElement as defineKbdGroup } from '@aranghat/base/kbd-group';
import { defineCustomElement as defineSkeleton } from '@aranghat/base/skeleton';
import { defineCustomElement as defineSpinner } from '@aranghat/base/spinner';
import { defineCustomElement as defineProgress } from '@aranghat/base/progress';
import { defineCustomElement as defineButtonGroup } from '@aranghat/base/button-group';
import { defineCustomElement as defineButtonGroupText } from '@aranghat/base/button-group-text';
import { defineCustomElement as defineInputGroup } from '@aranghat/base/input-group';
import { defineCustomElement as defineField } from '@aranghat/base/field';
import { defineCustomElement as defineFieldSet } from '@aranghat/base/field-set';
import { defineCustomElement as defineFieldGroup } from '@aranghat/base/field-group';
import { defineCustomElement as defineInputOtp } from '@aranghat/base/input-otp';
import { defineCustomElement as defineAspectRatio } from '@aranghat/base/aspect-ratio';
import { defineCustomElement as defineCard } from '@aranghat/base/card';
import { defineCustomElement as defineItem } from '@aranghat/base/item';
import { defineCustomElement as defineItemGroup } from '@aranghat/base/item-group';
import { defineCustomElement as defineEmpty } from '@aranghat/base/empty';
import { defineCustomElement as defineMarker } from '@aranghat/base/marker';
import { defineCustomElement as defineTable } from '@aranghat/base/table';
import { defineCustomElement as defineTypography } from '@aranghat/base/typography';
import { defineCustomElement as defineTooltip } from '@aranghat/components/tooltip';
import { defineCustomElement as definePopover } from '@aranghat/components/popover';
import { defineCustomElement as defineHoverCard } from '@aranghat/components/hover-card';
import { defineCustomElement as defineCollapsible } from '@aranghat/components/collapsible';
import { defineCustomElement as defineAccordion } from '@aranghat/components/accordion';
import { defineCustomElement as defineAccordionItem } from '@aranghat/components/accordion-item';
import { defineCustomElement as defineTabs } from '@aranghat/components/tabs';
import { defineCustomElement as defineTabPanel } from '@aranghat/components/tab-panel';
import { defineCustomElement as defineAlert } from '@aranghat/components/alert';
import { defineCustomElement as defineAvatar } from '@aranghat/components/avatar';
import { defineCustomElement as defineScrollArea } from '@aranghat/components/scroll-area';
import { defineCustomElement as defineResizable } from '@aranghat/components/resizable';
import { defineCustomElement as defineResizablePanel } from '@aranghat/components/resizable-panel';
import { defineCustomElement as defineResizableHandle } from '@aranghat/components/resizable-handle';
import { defineCustomElement as defineSelect } from '@aranghat/components/select';
import { defineCustomElement as defineSelectItem } from '@aranghat/components/select-item';
import { defineCustomElement as defineSelectGroup } from '@aranghat/components/select-group';
import { defineCustomElement as defineCommand } from '@aranghat/components/command';
import { defineCustomElement as defineCommandItem } from '@aranghat/components/command-item';
import { defineCustomElement as defineCommandGroup } from '@aranghat/components/command-group';
import { defineCustomElement as defineCombobox } from '@aranghat/components/combobox';
import { defineCustomElement as defineComboboxItem } from '@aranghat/components/combobox-item';
import { defineCustomElement as defineComboboxGroup } from '@aranghat/components/combobox-group';
import { defineCustomElement as defineCalendar } from '@aranghat/components/calendar';
import { defineCustomElement as defineDatePicker } from '@aranghat/components/date-picker';
import { defineCustomElement as defineToaster } from '@aranghat/components/toaster';
import { defineCustomElement as defineToast } from '@aranghat/components/toast';
import { defineCustomElement as defineCarousel } from '@aranghat/components/carousel';
import { defineCustomElement as defineCarouselItem } from '@aranghat/components/carousel-item';
import { defineCustomElement as defineBubble } from '@aranghat/components/bubble';
import { defineCustomElement as defineBubbleGroup } from '@aranghat/components/bubble-group';
import { defineCustomElement as defineMessage } from '@aranghat/components/message';
import { defineCustomElement as defineMessageGroup } from '@aranghat/components/message-group';
import { defineCustomElement as defineMessageScroller } from '@aranghat/components/message-scroller';
import { defineCustomElement as defineMessageScrollerItem } from '@aranghat/components/message-scroller-item';
import { defineCustomElement as defineAttachment } from '@aranghat/components/attachment';
import { defineCustomElement as defineAttachmentGroup } from '@aranghat/components/attachment-group';
import { defineCustomElement as defineQuestionnaire } from '@aranghat/components/questionnaire';
import './sandbox.css';

defineButton();
defineHello();
defineIcon();
defineHelloOverlay();
defineLabel();
defineInput();
defineTextarea();
defineCheckbox();
defineSwitch();
defineRadioGroup();
defineNativeSelect();
defineToggle();
defineToggleGroup();
defineSlider();
defineSeparator();
defineBadge();
defineKbd();
defineKbdGroup();
defineSkeleton();
defineSpinner();
defineProgress();
defineButtonGroup();
defineButtonGroupText();
defineInputGroup();
defineField();
defineFieldSet();
defineFieldGroup();
defineInputOtp();
defineAspectRatio();
defineCard();
defineItem();
defineItemGroup();
defineEmpty();
defineMarker();
defineTable();
defineTypography();
defineTooltip();
definePopover();
defineHoverCard();
defineCollapsible();
defineAccordion();
defineAccordionItem();
defineTabs();
defineTabPanel();
defineAlert();
defineAvatar();
defineScrollArea();
defineResizable();
defineResizablePanel();
defineResizableHandle();
defineSelect();
defineSelectItem();
defineSelectGroup();
defineCommand();
defineCommandItem();
defineCommandGroup();
defineCombobox();
defineComboboxItem();
defineComboboxGroup();
defineCalendar();
defineDatePicker();
defineToaster();
defineToast();
defineCarousel();
defineCarouselItem();
defineBubble();
defineBubbleGroup();
defineMessage();
defineMessageGroup();
defineMessageScroller();
defineMessageScrollerItem();
defineAttachment();
defineAttachmentGroup();
defineQuestionnaire();

// Every sample is a real file under src/samples/<component>/<example>.html — the
// docs site embeds these files verbatim, and the smoke test asserts each renders.
const samples = import.meta.glob('./samples/**/*.html', { query: '?raw', import: 'default', eager: true }) as Record<string, string>;
const app = document.getElementById('app')!;
for (const [path, html] of Object.entries(samples).sort()) {
  const id = path.replace('./samples/', '').replace(/\.html$/, '');
  const section = document.createElement('section');
  section.dataset.sample = id;
  section.innerHTML = `<h2>${id}</h2>${html}`;
  app.append(section);
}

// theme toggle for manual checks
document.addEventListener('keydown', (e) => {
  if (e.key === 'd' && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    const root = document.documentElement;
    root.dataset.theme = root.dataset.theme === 'dark' ? 'light' : 'dark';
  }
});
