import type { ComponentStories } from '@artui/stories';

const icon = (d: string) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${d}</svg>`;
const home = icon('<path d="M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8"/><path d="M3 10a2 2 0 0 1 .709-1.528l7-5.999a2 2 0 0 1 2.582 0l7 5.999A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>');
const inbox = icon('<polyline points="22 12 16 12 14 15 10 15 8 12 2 12"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/>');
const calendar = icon('<path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/>');
const search = icon('<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>');
const settings = icon('<path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"/><circle cx="12" cy="12" r="3"/>');
const folder = icon('<path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z"/>');
const plus = icon('<path d="M5 12h14"/><path d="M12 5v14"/>');
const more = icon('<circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/><circle cx="5" cy="12" r="1"/>');
const user = icon('<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>');
const box = icon('<path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><path d="m3.3 7 8.7 5 8.7-5"/><path d="M12 22V12"/>');

const item = (label: string, ic: string, extra = '', attrs = '') => `      <art-sidebar-menu-item${extra}>\n        <art-sidebar-menu-button href="#" tooltip="${label}"${attrs}>${ic}<span>${label}</span></art-sidebar-menu-button>\n      </art-sidebar-menu-item>`;
const platform = `  <art-sidebar-group label="Platform">\n    <art-sidebar-menu>\n${item('Home', home, '', ' active')}\n      <art-sidebar-menu-item>\n        <art-sidebar-menu-button href="#" tooltip="Inbox">${inbox}<span>Inbox</span></art-sidebar-menu-button>\n        <span slot="badge">24</span>\n      </art-sidebar-menu-item>\n${item('Calendar', calendar)}\n${item('Search', search)}\n${item('Settings', settings)}\n    </art-sidebar-menu>\n  </art-sidebar-group>`;
const projects = `  <art-sidebar-group label="Projects">\n    <art-button slot="action" variant="ghost" icon size="sm" aria-label="Add project">${plus}</art-button>\n    <art-sidebar-menu>\n      <art-sidebar-menu-item action-on-hover>\n        <art-sidebar-menu-button href="#" tooltip="Design Engineering">${folder}<span>Design Engineering</span></art-sidebar-menu-button>\n        <art-button slot="action" variant="ghost" icon size="sm" aria-label="More">${more}</art-button>\n      </art-sidebar-menu-item>\n      <art-sidebar-menu-item action-on-hover>\n        <art-sidebar-menu-button href="#" tooltip="Sales &amp; Marketing">${folder}<span>Sales &amp; Marketing</span></art-sidebar-menu-button>\n        <art-button slot="action" variant="ghost" icon size="sm" aria-label="More">${more}</art-button>\n      </art-sidebar-menu-item>\n    </art-sidebar-menu>\n  </art-sidebar-group>`;
const header = `  <art-sidebar-menu slot="header">\n    <art-sidebar-menu-item>\n      <art-sidebar-menu-button size="lg" tooltip="Acme Inc">${box}<span>Acme Inc</span></art-sidebar-menu-button>\n    </art-sidebar-menu-item>\n  </art-sidebar-menu>`;
const footer = `  <art-sidebar-menu slot="footer">\n    <art-sidebar-menu-item>\n      <art-sidebar-menu-button size="lg" tooltip="Account">${user}<span>shadcn</span></art-sidebar-menu-button>\n    </art-sidebar-menu-item>\n  </art-sidebar-menu>`;
const page = `<header style="display: flex; align-items: center; gap: var(--art-space-2); height: var(--art-space-14); padding-inline: var(--art-space-4)">\n    <art-sidebar-trigger></art-sidebar-trigger>\n    <art-separator orientation="vertical" style="height: var(--art-space-4)"></art-separator>\n    <art-breadcrumb>\n      <art-breadcrumb-item><a href="#">Building your application</a></art-breadcrumb-item>\n      <art-breadcrumb-item current>Data fetching</art-breadcrumb-item>\n    </art-breadcrumb>\n  </header>\n  <div style="display: grid; gap: var(--art-space-4); padding: var(--art-space-4)">\n    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: var(--art-space-4)">\n      <art-skeleton style="aspect-ratio: 16 / 9"></art-skeleton>\n      <art-skeleton style="aspect-ratio: 16 / 9"></art-skeleton>\n      <art-skeleton style="aspect-ratio: 16 / 9"></art-skeleton>\n    </div>\n    <art-skeleton style="height: var(--art-space-24)"></art-skeleton>\n  </div>`;
const sidebar = (attrs = '', body = `${header}\n${platform}\n${projects}\n${footer}`) => `<art-sidebar${attrs}>\n${body}\n</art-sidebar>`;
const shell = (provider = '', sb = sidebar(), inset = page, rightSide = false) => `<art-sidebar-provider${provider}>\n${rightSide ? '' : `${sb}\n`}<art-sidebar-inset>\n  ${inset}\n</art-sidebar-inset>${rightSide ? `\n${sb}` : ''}\n</art-sidebar-provider>`;

export const stories: ComponentStories = {
  tag: 'art-sidebar',
  tier: 'navigation',
  variants: ['sidebar', 'floating', 'inset'],
  sizes: [],
  states: ['default', 'hover', 'focus-visible'],
  directional: true,
  screenshot: 'viewport',
  frame: 'shell',
  examples: {
    basic: { title: 'Basic', render: () => shell(), note: 'An `art-sidebar-provider` holds the sidebar and the `art-sidebar-inset` (the page). Groups hold menus of items; a button with `href` is a link, `active` marks the current page, `badge` and `action` slots sit at the end of a row. `art-sidebar-trigger` (and ⌘ / Ctrl + B) toggles; below the md breakpoint the sidebar opens as a sheet.' },
    icon: { title: 'Collapse to icons', render: () => shell(' open="false"', sidebar(' collapsible="icon"')), note: '`collapsible="icon"` keeps a rail of icons when collapsed; `tooltip` on a button names it there. `open="false"` on the provider starts collapsed.' },
    floating: { title: 'Floating', render: () => shell('', sidebar(' variant="floating"')), note: '`variant="floating"` renders the sidebar as a bordered card inset from the edge.' },
    inset: { title: 'Inset', render: () => shell('', sidebar(' variant="inset"')), note: '`variant="inset"` paints the frame in the sidebar colour and floats the page as a card.' },
    right: { title: 'Right side', render: () => shell('', sidebar(' side="right"'), page, true), note: '`side="right"` (put the sidebar after the inset). Sides are logical: `left` is the inline start and mirrors in RTL.' },
    submenu: { title: 'Collapsible groups', render: () => shell('', sidebar('', `${header}\n  <art-sidebar-group label="Documentation">\n    <art-sidebar-menu>\n      <art-sidebar-menu-item open>\n        <art-sidebar-menu-button tooltip="Getting started">${box}<span>Getting started</span></art-sidebar-menu-button>\n        <art-sidebar-menu-sub>\n          <art-sidebar-menu-item><art-sidebar-menu-button href="#" active><span>Installation</span></art-sidebar-menu-button></art-sidebar-menu-item>\n          <art-sidebar-menu-item><art-sidebar-menu-button href="#"><span>Project structure</span></art-sidebar-menu-button></art-sidebar-menu-item>\n        </art-sidebar-menu-sub>\n      </art-sidebar-menu-item>\n      <art-sidebar-menu-item>\n        <art-sidebar-menu-button tooltip="Building">${folder}<span>Building your application</span></art-sidebar-menu-button>\n        <art-sidebar-menu-sub>\n          <art-sidebar-menu-item><art-sidebar-menu-button href="#"><span>Routing</span></art-sidebar-menu-button></art-sidebar-menu-item>\n          <art-sidebar-menu-item><art-sidebar-menu-button href="#"><span>Data fetching</span></art-sidebar-menu-button></art-sidebar-menu-item>\n        </art-sidebar-menu-sub>\n      </art-sidebar-menu-item>\n    </art-sidebar-menu>\n  </art-sidebar-group>\n${footer}`)), note: 'An item with a nested `art-sidebar-menu-sub` becomes a disclosure: its button toggles `open` (chevron, `aria-expanded`). Nested lists hide when the sidebar collapses to icons.' },
    rail: { title: 'Rail', render: () => shell('', sidebar(' rail')), note: '`rail` adds a thin strip on the outer edge that toggles the sidebar on click (the line shows on hover).' },
    app: { title: 'With TopNav', render: () => shell('', sidebar(), `<art-top-nav label="Page">\n    <art-sidebar-trigger slot="brand"></art-sidebar-trigger>\n    <a href="#" aria-current="page">Overview</a>\n    <a href="#">Reports</a>\n    <a href="#">Members</a>\n    <art-button slot="end" variant="outline" size="sm">Share</art-button>\n  </art-top-nav>\n  <div style="display: grid; gap: var(--art-space-4); padding: var(--art-space-4)">\n    <art-skeleton style="height: var(--art-space-24)"></art-skeleton>\n  </div>`), note: 'An `art-top-nav` at the top of the inset with the trigger in its `brand` slot gives the classic app shell.' },
    loading: { title: 'Loading', render: () => shell('', sidebar('', `${header}\n  <art-sidebar-group label="Projects">\n    <art-sidebar-menu>\n${[1, 2, 3, 4].map((i) => `      <art-sidebar-menu-item><div style="display: flex; align-items: center; gap: var(--art-space-2); height: var(--art-space-8); padding-inline: var(--art-space-2)"><art-skeleton style="width: var(--art-space-4); height: var(--art-space-4); border-radius: var(--art-radius-md)"></art-skeleton><art-skeleton style="height: var(--art-space-4); flex: 1; max-width: ${[60, 75, 50, 65][i - 1]}%"></art-skeleton></div></art-sidebar-menu-item>`).join('\n')}\n    </art-sidebar-menu>\n  </art-sidebar-group>\n${footer}`)), note: 'While data loads, rows hold `art-skeleton`s instead of buttons (shadcn `SidebarMenuSkeleton`).' },
  },
  render: ({ variant }) => shell(' open-mobile', sidebar(variant === 'sidebar' ? '' : ` variant="${variant}"`)),
  focusTarget: 'art-sidebar-menu-button [part="button"]',
  docs: {
    description: 'A composable, collapsible app sidebar. shadcn/ui parity: provider, sidebar, groups, menus, trigger, rail, inset; off-canvas below the md breakpoint.',
    usage: 'Wrap the page in `art-sidebar-provider`, put an `art-sidebar` (header / default / footer slots) and an `art-sidebar-inset` inside. Groups hold `art-sidebar-menu`s of `art-sidebar-menu-item`s, each with an `art-sidebar-menu-button` (`href`, `active`, `tooltip`) and optional `action` / `badge` slots or a nested `art-sidebar-menu-sub`. `art-sidebar-trigger` toggles from anywhere. Listen to `open-change` on the provider; React `<SidebarProvider open onOpenChange>`, Vue `v-model:open`, Angular `[open] (openChange)`. Width: `--art-sidebar-width` on the provider.',
    requires: ['base'],
    keyboard: [['⌘ / Ctrl + B', 'Toggle the sidebar'], ['Tab', 'Move through the sidebar controls, then the page'], ['Enter / Space', 'Activate a button; toggle a nested list'], ['Escape', 'Close the off-canvas sidebar (mobile)']],
    roles: 'The sidebar is a `<nav>` named by `label`; menus are lists (`role="list"` / `listitem`); buttons are native `<button>`s or `<a>`s with `aria-current="page"` when `active` and `aria-expanded` on disclosure items. The trigger carries `aria-expanded`. On mobile the sidebar is a `role="dialog"` sheet with a focus trap and a scrim.',
    apg: 'https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/',
    states: '`hover` and `focus-visible` on buttons, `active` (current page) and `disabled` on buttons, expanded / collapsed sidebar with motion, open / closed sheet on mobile. `loading` is composed with `art-skeleton`; `invalid` does not apply.',
    tokens: [['`--art-sidebar-width`, `--art-sidebar-width-icon`, `--art-sidebar-width-mobile`', 'widths (expanded, icons, sheet)'], ['`--art-color-bg-sidebar`, `--art-color-bg-sidebar-accent`', 'surface, hover / active rows'], ['`--art-color-fg-default`, `--art-color-fg-muted`, `--art-color-border-default`', 'text, group labels, borders'], ['`--art-color-bg-overlay`, `--art-z-modal`, `--art-z-sticky`', 'sheet scrim and stacking'], ['`--art-radius-md`, `--art-radius-lg`, `--art-radius-xl`, `--art-shadow-raised`', 'rows, floating card, inset card'], ['`--art-space-2`, `--art-space-7`, `--art-space-8`, `--art-space-12`', 'padding and row heights'], ['`--art-duration-base`, `--art-duration-slow`, `--art-ease-out`', 'collapse and sheet motion']],
    dos: [['Group destinations under short labels', 'Put thirty flat links in one menu'], ['Give icon-mode buttons a `tooltip`', 'Collapse to icons nobody can name'], ['Keep the trigger visible on every page', 'Hide the only way to reopen the sidebar']],
  },
};
