/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * One destination in the panel: a leading icon, a label, and an optional badge for work that is
     * not shipped yet. While the panel is collapsed only the icon shows, and the label moves into a
     * tooltip — the same treatment the rail's items get.
     */
    interface ArtNavLink {
        /**
          * Marks the current page (`aria-current="page"`).
          * @default false
         */
        "active": boolean;
        /**
          * Trailing badge — "Soon" for a destination that is not live yet.
         */
        "badge"?: string;
        /**
          * Set by the enclosing `art-nav-section` when the panel collapses — not something you set.
          * @default false
         */
        "collapsed": boolean;
        /**
          * Disabled: no interaction, no events. Pair it with `badge` to say why.
          * @default false
         */
        "disabled": boolean;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
    }
    /**
     * Nav Rail — a two-level application sidebar: a permanent icon rail that switches context, beside
     * a secondary panel that lists the sections of the context you are in. The panel collapses to
     * icons; the rail never does.
     * The rail carries `art-nav-rail-item`s; the panel carries `art-nav-section`s of `art-nav-link`s.
     * Everything else — the brand mark, the workspace switcher, the promo card, the user row — is a
     * slot, because those belong to the product, not to the design system.
     */
    interface ArtNavRail {
        /**
          * Panel collapsed to icons. The rail is always icons.
          * @default false
         */
        "collapsed": boolean;
        /**
          * Hide the collapse button (the panel is then controlled by `collapsed` alone).
          * @default false
         */
        "hideToggle": boolean;
        /**
          * Accessible name of the panel's navigation.
          * @default 'Sections'
         */
        "label": string;
        /**
          * Accessible name of the rail's navigation.
          * @default 'Contexts'
         */
        "railLabel": string;
        /**
          * Accessible name of the collapse button.
          * @default 'Toggle the navigation panel'
         */
        "toggleLabel": string;
    }
    /**
     * One context in the rail: an icon that is always icon-only, so its name is announced by the
     * accessible name and shown in a tooltip on hover or keyboard focus.
     */
    interface ArtNavRailItem {
        /**
          * Marks the current context (`aria-current="page"`).
          * @default false
         */
        "active": boolean;
        /**
          * Disabled: no interaction, no events.
          * @default false
         */
        "disabled": boolean;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * The name: the accessible name of the control and the tooltip's text. Required.
         */
        "label": string;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
    }
    /**
     * A labelled group of `art-nav-link`s in the panel. The label is a heading for the list it
     * introduces; when the panel collapses the label goes and a rule takes its place, so the grouping
     * survives without the words.
     */
    interface ArtNavSection {
        /**
          * Set by the enclosing `art-nav-rail` when its panel collapses — not something you set.
          * @default false
         */
        "collapsed": boolean;
        /**
          * The group heading ("Portfolio", "Operations").
         */
        "label"?: string;
    }
}
export interface ArtNavRailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArtNavRailElement;
}
declare global {
    /**
     * One destination in the panel: a leading icon, a label, and an optional badge for work that is
     * not shipped yet. While the panel is collapsed only the icon shows, and the label moves into a
     * tooltip — the same treatment the rail's items get.
     */
    interface HTMLArtNavLinkElement extends Components.ArtNavLink, HTMLStencilElement {
    }
    var HTMLArtNavLinkElement: {
        prototype: HTMLArtNavLinkElement;
        new (): HTMLArtNavLinkElement;
    };
    interface HTMLArtNavRailElementEventMap {
        "collapsed-change": { collapsed: boolean };
    }
    /**
     * Nav Rail — a two-level application sidebar: a permanent icon rail that switches context, beside
     * a secondary panel that lists the sections of the context you are in. The panel collapses to
     * icons; the rail never does.
     * The rail carries `art-nav-rail-item`s; the panel carries `art-nav-section`s of `art-nav-link`s.
     * Everything else — the brand mark, the workspace switcher, the promo card, the user row — is a
     * slot, because those belong to the product, not to the design system.
     */
    interface HTMLArtNavRailElement extends Components.ArtNavRail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArtNavRailElementEventMap>(type: K, listener: (this: HTMLArtNavRailElement, ev: ArtNavRailCustomEvent<HTMLArtNavRailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArtNavRailElementEventMap>(type: K, listener: (this: HTMLArtNavRailElement, ev: ArtNavRailCustomEvent<HTMLArtNavRailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArtNavRailElement: {
        prototype: HTMLArtNavRailElement;
        new (): HTMLArtNavRailElement;
    };
    /**
     * One context in the rail: an icon that is always icon-only, so its name is announced by the
     * accessible name and shown in a tooltip on hover or keyboard focus.
     */
    interface HTMLArtNavRailItemElement extends Components.ArtNavRailItem, HTMLStencilElement {
    }
    var HTMLArtNavRailItemElement: {
        prototype: HTMLArtNavRailItemElement;
        new (): HTMLArtNavRailItemElement;
    };
    /**
     * A labelled group of `art-nav-link`s in the panel. The label is a heading for the list it
     * introduces; when the panel collapses the label goes and a rule takes its place, so the grouping
     * survives without the words.
     */
    interface HTMLArtNavSectionElement extends Components.ArtNavSection, HTMLStencilElement {
    }
    var HTMLArtNavSectionElement: {
        prototype: HTMLArtNavSectionElement;
        new (): HTMLArtNavSectionElement;
    };
    interface HTMLElementTagNameMap {
        "art-nav-link": HTMLArtNavLinkElement;
        "art-nav-rail": HTMLArtNavRailElement;
        "art-nav-rail-item": HTMLArtNavRailItemElement;
        "art-nav-section": HTMLArtNavSectionElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * One destination in the panel: a leading icon, a label, and an optional badge for work that is
     * not shipped yet. While the panel is collapsed only the icon shows, and the label moves into a
     * tooltip — the same treatment the rail's items get.
     */
    interface ArtNavLink {
        /**
          * Marks the current page (`aria-current="page"`).
          * @default false
         */
        "active"?: boolean;
        /**
          * Trailing badge — "Soon" for a destination that is not live yet.
         */
        "badge"?: string;
        /**
          * Set by the enclosing `art-nav-section` when the panel collapses — not something you set.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Disabled: no interaction, no events. Pair it with `badge` to say why.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
    }
    /**
     * Nav Rail — a two-level application sidebar: a permanent icon rail that switches context, beside
     * a secondary panel that lists the sections of the context you are in. The panel collapses to
     * icons; the rail never does.
     * The rail carries `art-nav-rail-item`s; the panel carries `art-nav-section`s of `art-nav-link`s.
     * Everything else — the brand mark, the workspace switcher, the promo card, the user row — is a
     * slot, because those belong to the product, not to the design system.
     */
    interface ArtNavRail {
        /**
          * Panel collapsed to icons. The rail is always icons.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * Hide the collapse button (the panel is then controlled by `collapsed` alone).
          * @default false
         */
        "hideToggle"?: boolean;
        /**
          * Accessible name of the panel's navigation.
          * @default 'Sections'
         */
        "label"?: string;
        /**
          * Emitted when the user collapses or expands the panel; `detail.collapsed`.
         */
        "onCollapsed-change"?: (event: ArtNavRailCustomEvent<{ collapsed: boolean }>) => void;
        /**
          * Accessible name of the rail's navigation.
          * @default 'Contexts'
         */
        "railLabel"?: string;
        /**
          * Accessible name of the collapse button.
          * @default 'Toggle the navigation panel'
         */
        "toggleLabel"?: string;
    }
    /**
     * One context in the rail: an icon that is always icon-only, so its name is announced by the
     * accessible name and shown in a tooltip on hover or keyboard focus.
     */
    interface ArtNavRailItem {
        /**
          * Marks the current context (`aria-current="page"`).
          * @default false
         */
        "active"?: boolean;
        /**
          * Disabled: no interaction, no events.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Render as a link.
         */
        "href"?: string;
        /**
          * The name: the accessible name of the control and the tooltip's text. Required.
         */
        "label": string;
        /**
          * Link rel (only with `href`).
         */
        "rel"?: string;
        /**
          * Link target (only with `href`).
         */
        "target"?: string;
    }
    /**
     * A labelled group of `art-nav-link`s in the panel. The label is a heading for the list it
     * introduces; when the panel collapses the label goes and a rule takes its place, so the grouping
     * survives without the words.
     */
    interface ArtNavSection {
        /**
          * Set by the enclosing `art-nav-rail` when its panel collapses — not something you set.
          * @default false
         */
        "collapsed"?: boolean;
        /**
          * The group heading ("Portfolio", "Operations").
         */
        "label"?: string;
    }

    interface ArtNavLinkAttributes {
        "active": boolean;
        "href": string;
        "target": string;
        "rel": string;
        "disabled": boolean;
        "badge": string;
        "collapsed": boolean;
    }
    interface ArtNavRailAttributes {
        "collapsed": boolean;
        "label": string;
        "railLabel": string;
        "toggleLabel": string;
        "hideToggle": boolean;
    }
    interface ArtNavRailItemAttributes {
        "label": string;
        "active": boolean;
        "href": string;
        "target": string;
        "rel": string;
        "disabled": boolean;
    }
    interface ArtNavSectionAttributes {
        "label": string;
        "collapsed": boolean;
    }

    interface IntrinsicElements {
        "art-nav-link": Omit<ArtNavLink, keyof ArtNavLinkAttributes> & { [K in keyof ArtNavLink & keyof ArtNavLinkAttributes]?: ArtNavLink[K] } & { [K in keyof ArtNavLink & keyof ArtNavLinkAttributes as `attr:${K}`]?: ArtNavLinkAttributes[K] } & { [K in keyof ArtNavLink & keyof ArtNavLinkAttributes as `prop:${K}`]?: ArtNavLink[K] };
        "art-nav-rail": Omit<ArtNavRail, keyof ArtNavRailAttributes> & { [K in keyof ArtNavRail & keyof ArtNavRailAttributes]?: ArtNavRail[K] } & { [K in keyof ArtNavRail & keyof ArtNavRailAttributes as `attr:${K}`]?: ArtNavRailAttributes[K] } & { [K in keyof ArtNavRail & keyof ArtNavRailAttributes as `prop:${K}`]?: ArtNavRail[K] };
        "art-nav-rail-item": Omit<ArtNavRailItem, keyof ArtNavRailItemAttributes> & { [K in keyof ArtNavRailItem & keyof ArtNavRailItemAttributes]?: ArtNavRailItem[K] } & { [K in keyof ArtNavRailItem & keyof ArtNavRailItemAttributes as `attr:${K}`]?: ArtNavRailItemAttributes[K] } & { [K in keyof ArtNavRailItem & keyof ArtNavRailItemAttributes as `prop:${K}`]?: ArtNavRailItem[K] } & OneOf<"label", ArtNavRailItem["label"], ArtNavRailItemAttributes["label"]>;
        "art-nav-section": Omit<ArtNavSection, keyof ArtNavSectionAttributes> & { [K in keyof ArtNavSection & keyof ArtNavSectionAttributes]?: ArtNavSection[K] } & { [K in keyof ArtNavSection & keyof ArtNavSectionAttributes as `attr:${K}`]?: ArtNavSectionAttributes[K] } & { [K in keyof ArtNavSection & keyof ArtNavSectionAttributes as `prop:${K}`]?: ArtNavSection[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * One destination in the panel: a leading icon, a label, and an optional badge for work that is
             * not shipped yet. While the panel is collapsed only the icon shows, and the label moves into a
             * tooltip — the same treatment the rail's items get.
             */
            "art-nav-link": LocalJSX.IntrinsicElements["art-nav-link"] & JSXBase.HTMLAttributes<HTMLArtNavLinkElement>;
            /**
             * Nav Rail — a two-level application sidebar: a permanent icon rail that switches context, beside
             * a secondary panel that lists the sections of the context you are in. The panel collapses to
             * icons; the rail never does.
             * The rail carries `art-nav-rail-item`s; the panel carries `art-nav-section`s of `art-nav-link`s.
             * Everything else — the brand mark, the workspace switcher, the promo card, the user row — is a
             * slot, because those belong to the product, not to the design system.
             */
            "art-nav-rail": LocalJSX.IntrinsicElements["art-nav-rail"] & JSXBase.HTMLAttributes<HTMLArtNavRailElement>;
            /**
             * One context in the rail: an icon that is always icon-only, so its name is announced by the
             * accessible name and shown in a tooltip on hover or keyboard focus.
             */
            "art-nav-rail-item": LocalJSX.IntrinsicElements["art-nav-rail-item"] & JSXBase.HTMLAttributes<HTMLArtNavRailItemElement>;
            /**
             * A labelled group of `art-nav-link`s in the panel. The label is a heading for the list it
             * introduces; when the panel collapses the label goes and a rule takes its place, so the grouping
             * survives without the words.
             */
            "art-nav-section": LocalJSX.IntrinsicElements["art-nav-section"] & JSXBase.HTMLAttributes<HTMLArtNavSectionElement>;
        }
    }
}
